using System.Collections.Generic;

namespace GasStation.Localization
{
    /// <summary>
    /// Source of all UI strings (Russian and English). The editor menu
    /// "GasStation/Localization/Setup" writes them into the Unity Localization string table "GasStation";
    /// at runtime the table is used, and this dictionary is the fallback when the package is not set up.
    /// Strings use string.Format placeholders ({0}, {0:0}, …).
    /// </summary>
    public static class LocTable
    {
        public const string TableName = "GasStation";

        public static readonly Dictionary<string, string[]> Entries = new()
        {
            // Fuel, products
            { "fuel.Petrol92", new[] { "АИ-92", "Regular 92" } },
            { "fuel.Petrol95", new[] { "АИ-95", "Premium 95" } },
            { "fuel.Diesel", new[] { "ДТ", "Diesel" } },
            { "product.Water", new[] { "Вода", "Water" } },
            { "product.Coffee", new[] { "Кофе", "Coffee" } },
            { "product.Snacks", new[] { "Снеки", "Snacks" } },
            { "product.MotorOil", new[] { "Моторное масло", "Motor oil" } },
            { "product.Souvenir", new[] { "Сувениры", "Souvenirs" } },

            // Upgrades
            { "upgrade.name.PumpSpeed", new[] { "Быстрые насосы", "Fast pumps" } },
            { "upgrade.name.TankCapacity", new[] { "Большие резервуары", "Bigger tanks" } },
            { "upgrade.name.Comfort", new[] { "Навес и кофе", "Shade and coffee" } },
            { "upgrade.name.Advertising", new[] { "Реклама", "Advertising" } },
            { "upgrade.name.Attendant", new[] { "Заправщик", "Attendant" } },
            { "upgrade.name.ExtraPump", new[] { "Новая колонка", "Extra pump" } },
            { "upgrade.name.Janitor", new[] { "Уборщик", "Janitor" } },
            { "upgrade.name.Mechanic", new[] { "Механик", "Mechanic" } },
            { "upgrade.name.CarWash", new[] { "Автомойка", "Car wash" } },
            { "upgrade.name.SupplyManager", new[] { "Завхоз", "Supply manager" } },
            { "upgrade.name.TruckParking", new[] { "Стоянка для фур", "Truck parking" } },
            { "upgrade.name.TireService", new[] { "Шиномонтаж", "Tire service" } },
            { "upgrade.name.Motel", new[] { "Мотель", "Motel" } },
            { "upgrade.desc.PumpSpeed", new[] { "+50% скорости заправки", "+50% fueling speed" } },
            { "upgrade.desc.TankCapacity", new[] { "+1000 л к каждому резервуару", "+1000 L to every tank" } },
            { "upgrade.desc.Comfort", new[] { "клиенты ждут на 20% дольше", "customers wait 20% longer" } },
            { "upgrade.desc.Advertising", new[] { "+25% клиентов", "+25% customers" } },
            { "upgrade.desc.ExtraPump", new[] { "открывает ещё одну колонку", "opens one more pump" } },
            { "upgrade.desc.CarWash", new[] { "открывает мойку, уровни — быстрее и дороже", "opens the car wash; levels are faster and pricier" } },
            { "upgrade.desc.SupplyManager", new[] { "сам заказывает топливо и товар; ур.2 −10%, ур.3 быстрее; $50/день", "reorders fuel and goods; lvl 2 −10%, lvl 3 faster; $50/day" } },
            { "upgrade.desc.TruckParking", new[] { "+2 места для ночёвки дальнобойщиков", "+2 overnight spots for truckers" } },
            { "upgrade.desc.TireService", new[] { "меняете шины за деньги; уровни — быстрее и дороже", "change tires for money; levels are faster and pricier" } },
            { "upgrade.desc.Motel", new[] { "+2 номера для ночёвки путешественников, номера дороже", "+2 rooms for travellers, pricier rooms" } },

            // Staff
            { "role.Attendant", new[] { "заправщик", "attendant" } },
            { "role.Janitor", new[] { "уборщик", "janitor" } },
            { "role.Mechanic", new[] { "механик", "mechanic" } },
            { "role.Cashier", new[] { "кассир", "cashier" } },
            { "duty.Attendant", new[] { "сам заправляет машины", "fuels cars" } },
            { "duty.Janitor", new[] { "убирает мусор и туалет", "cleans litter and the restroom" } },
            { "duty.Mechanic", new[] { "чинит колонки, меняет шины", "repairs pumps, changes tires" } },
            { "duty.Cashier", new[] { "ускоряет покупки в магазине", "speeds up shopping" } },
            { "reference.2", new[] { "отличные рекомендации", "excellent references" } },
            { "reference.1", new[] { "обычные рекомендации", "average references" } },
            { "reference.0", new[] { "сомнительные рекомендации", "dubious references" } },
            { "staff.name.0", new[] { "Иван", "John" } },
            { "staff.name.1", new[] { "Ольга", "Olivia" } },
            { "staff.name.2", new[] { "Пётр", "Peter" } },
            { "staff.name.3", new[] { "Анна", "Anna" } },
            { "staff.name.4", new[] { "Сергей", "Sam" } },
            { "staff.name.5", new[] { "Мария", "Mary" } },
            { "staff.name.6", new[] { "Алексей", "Alex" } },
            { "staff.name.7", new[] { "Елена", "Helen" } },
            { "staff.name.8", new[] { "Дмитрий", "Daniel" } },
            { "staff.name.9", new[] { "Наталья", "Natalie" } },
            { "staff.name.10", new[] { "Андрей", "Andrew" } },
            { "staff.name.11", new[] { "Татьяна", "Tina" } },
            { "staff.name.12", new[] { "Михаил", "Michael" } },
            { "staff.name.13", new[] { "Ирина", "Irene" } },
            { "staff.name.14", new[] { "Николай", "Nick" } },
            { "staff.name.15", new[] { "Светлана", "Susan" } },

            // Paint, customers
            { "scheme.0", new[] { "Облезлая краска", "Peeling paint" } },
            { "scheme.1", new[] { "Классика", "Classic" } },
            { "scheme.2", new[] { "Пустынный закат", "Desert sunset" } },
            { "scheme.3", new[] { "Неон 80-х", "80s neon" } },
            { "customer.Regular", new[] { "клиент", "customer" } },
            { "customer.Trucker", new[] { "дальнобойщик", "trucker" } },
            { "customer.Hurry", new[] { "торопыга", "in a hurry" } },
            { "customer.Tourist", new[] { "турист", "tourist" } },
            { "customer.Thief", new[] { "подозрительный тип", "shady type" } },
            { "customer.Critic", new[] { "критик", "critic" } },
            { "customer.Biker", new[] { "байкер", "biker" } },
            { "customer.Emergency", new[] { "скорая / полиция", "ambulance / police" } },
            { "customer.TourBus", new[] { "туристический автобус", "tour bus" } },
            { "customer.TowTruck", new[] { "эвакуатор", "tow truck" } },

            // Quests
            { "quest.title.0", new[] { "Заброшенная заправка", "Abandoned station" } },
            { "quest.title.1", new[] { "Первые клиенты", "First customers" } },
            { "quest.title.2", new[] { "Наводим порядок", "Tidying up" } },
            { "quest.title.3", new[] { "Бензовоз", "Fuel truck" } },
            { "quest.title.4", new[] { "Первое вложение", "First investment" } },
            { "quest.title.5", new[] { "Постоянные клиенты", "Regulars" } },
            { "quest.title.6", new[] { "Генеральная уборка", "Spring cleaning" } },
            { "quest.title.7", new[] { "Хорошая репутация", "Good name" } },
            { "quest.title.8", new[] { "Прибыльный день", "Profitable day" } },
            { "quest.title.9", new[] { "Расширение", "Expansion" } },
            { "quest.title.10", new[] { "Идеальная чистота", "Spotless" } },
            { "quest.title.11", new[] { "Колонка не работает", "Broken pump" } },
            { "quest.title.12", new[] { "Растущая слава", "Rising fame" } },
            { "quest.title.13", new[] { "Держи вора!", "Stop, thief!" } },
            { "quest.title.14", new[] { "Первые покупки", "First sales" } },
            { "quest.title.15", new[] { "Автомойка", "Car wash" } },
            { "quest.title.16", new[] { "Туалет", "Restroom" } },
            { "quest.title.17", new[] { "Ночлег", "A place to sleep" } },
            { "quest.title.18", new[] { "Новый облик", "Fresh look" } },
            { "quest.title.19", new[] { "Шиномонтаж", "Tire service" } },
            { "quest.title.20", new[] { "Первый сотрудник", "First employee" } },
            { "quest.title.21", new[] { "Мотель у дороги", "Roadside motel" } },
            { "quest.title.daily", new[] { "Задание дня", "Daily task" } },
            { "quest.goal.CollectTrash", new[] { "Собери мусор (E): {0}/{1:0}", "Pick up litter (E): {0}/{1:0}" } },
            { "quest.goal.ServeCustomers", new[] { "Обслужи клиентов: {0}/{1:0}", "Serve customers: {0}/{1:0}" } },
            { "quest.goal.OrderFuel", new[] { "Закажи бензовоз (O): {0}/{1:0}", "Order a fuel truck (O): {0}/{1:0}" } },
            { "quest.goal.BuyUpgrade", new[] { "Купи улучшение (Tab): {0}/{1:0}", "Buy an upgrade (Tab): {0}/{1:0}" } },
            { "quest.goal.Cleanliness", new[] { "Доведи чистоту до {1:0}%: сейчас {0}%", "Get cleanliness to {1:0}%: now {0}%" } },
            { "quest.goal.Reputation", new[] { "Подними репутацию до {1:0}%: сейчас {0}%", "Raise reputation to {1:0}%: now {0}%" } },
            { "quest.goal.DayIncome", new[] { "Заработай за день ${1:0}: сейчас ${0}", "Earn ${1:0} in one day: now ${0}" } },
            { "quest.goal.OpenPumps", new[] { "Открой новую колонку (Tab): {0}/1", "Open a new pump (Tab): {0}/1" } },
            { "quest.goal.RepairPump", new[] { "Почини колонку (E рядом со сломанной): {0}/{1:0}", "Repair a pump (E next to it): {0}/{1:0}" } },
            { "quest.goal.StationLevel", new[] { "Подними уровень станции до {1:0}: сейчас {0}", "Reach station level {1:0}: now {0}" } },
            { "quest.goal.CatchThief", new[] { "Стой рядом с машиной вора, когда он заправляется: {0}/1", "Stand next to a thief's car while it fuels: {0}/1" } },
            { "quest.goal.SellProducts", new[] { "Продай товары в магазине (M — ассортимент): {0}/{1:0}", "Sell goods in the shop (M — stock): {0}/{1:0}" } },
            { "quest.goal.OpenCarWash", new[] { "Открой автомойку (Tab): {0}/1", "Open the car wash (Tab): {0}/1" } },
            { "quest.goal.CleanRestroom", new[] { "Убери туалет (E у двери): {0}/1", "Clean the restroom (E at the door): {0}/1" } },
            { "quest.goal.HostTruckers", new[] { "Прими дальнобойщиков на ночь (Стоянка для фур): {0}/{1:0}", "Host truckers overnight (Truck parking): {0}/{1:0}" } },
            { "quest.goal.PaintStation", new[] { "Перекрась станцию (C): {0}/1", "Repaint the station (C): {0}/1" } },
            { "quest.goal.ChangeTires", new[] { "Поменяй шины клиентам (E у бокса шиномонтажа): {0}/{1:0}", "Change customers' tires (E at the tire bay): {0}/{1:0}" } },
            { "quest.goal.HireWorker", new[] { "Найми сотрудника (H): {0}/1", "Hire an employee (H): {0}/1" } },
            { "quest.goal.HostGuests", new[] { "Прими гостей в мотеле (Tab → «Мотель»): {0}/{1:0}", "Host motel guests (Tab → Motel): {0}/{1:0}" } },
            { "quest.reward.both", new[] { "${0:0} и +{1:0}% репутации", "${0:0} and +{1:0}% reputation" } },
            { "quest.reward.money", new[] { "${0:0}", "${0:0}" } },
            { "quest.reward.reputation", new[] { "+{0:0}% репутации", "+{0:0}% reputation" } },
            { "quest.header", new[] { "Задание: {0}", "Task: {0}" } },
            { "quest.reward", new[] { "Награда: {0}", "Reward: {0}" } },
            { "quest.completed", new[] { "Задание выполнено: {0}! Награда: {1}", "Task complete: {0}! Reward: {1}" } },

            // HUD: status
            { "hud.help", new[] {
                "WASD — ходить   E / ЛКМ — действие   1/2/3 — топливо   +/- — цена   O — заказать 500 л\nTab — улучшения   M — магазин   C — покраска   H — персонал   J — достижения   K — постоянные клиенты   F — финансы   B — стройка   N — ноутбук\nT — скорость   R — радио   L — язык   F1 — подсказки   F5 — сохранить   F9 — загрузить   Esc — меню",
                "WASD — walk   E / LMB — action   1/2/3 — fuel   +/- — price   O — order 500 L\nTab — upgrades   M — shop   C — paint   H — staff   J — achievements   K — regulars   F — finances   B — build   N — laptop\nT — speed   R — radio   L — language   F1 — hints   F5 — save   F9 — load   Esc — menu" } },
            { "hud.day", new[] { "День {0}   {1:00}:{2:00}", "Day {0}   {1:00}:{2:00}" } },
            { "hud.money", new[] { "Деньги: ${0:0}", "Money: ${0:0}" } },
            { "hud.reputation", new[] { "Репутация: {0:0}%", "Reputation: {0:0}%" } },
            { "hud.cleanliness", new[] { "Чистота: {0:0}% (мусора: {1})", "Cleanliness: {0:0}% (litter: {1})" } },
            { "hud.staff", new[] { "Персонал: {0} чел., зарплаты ${1:0}/день", "Staff: {0}, wages ${1:0}/day" } },
            { "hud.level.max", new[] { "Уровень станции: {0} (макс.)", "Station level: {0} (max)" } },
            { "hud.level", new[] { "Уровень станции: {0}   опыт {1:0}/{2:0}", "Station level: {0}   xp {1:0}/{2:0}" } },
            { "hud.event", new[] { "Событие: {0} (ещё {1:0.0} ч)", "Event: {0} ({1:0.0} h left)" } },
            { "event.RushHour", new[] { "Час пик", "Rush hour" } },
            { "event.Sandstorm", new[] { "Песчаная буря", "Sandstorm" } },
            { "hud.today", new[] { "Сегодня: +${0:0} / -${1:0}", "Today: +${0:0} / -${1:0}" } },
            { "hud.served", new[] { "Обслужено: {0}   Уехали: {1}", "Served: {0}   Lost: {1}" } },
            { "hud.fuel", new[] { "{0}: {1:0}/{2:0} л   ${3:0.00} (рынок ${4:0.00})", "{0}: {1:0}/{2:0} L   ${3:0.00} (market ${4:0.00})" } },
            { "hud.fuel.pending", new[] { "   +{0:0} л в пути", "   +{0:0} L on the way" } },

            // HUD: facilities and pumps
            { "hud.queue", new[] { "Очередь: {0}   Машин на станции: {1}", "Queue: {0}   Cars on site: {1}" } },
            { "hud.wash", new[] { "Мойка: {0}", "Car wash: {0}" } },
            { "hud.wash.closed", new[] { "закрыта (улучшение «Автомойка»)", "closed (Car wash upgrade)" } },
            { "hud.wash.working", new[] { "моет машину, ещё {0:0} с", "washing, {0:0} s left" } },
            { "hud.wash.arriving", new[] { "машина подъезжает", "car arriving" } },
            { "hud.free.f", new[] { "свободна", "free" } },
            { "hud.free.m", new[] { "свободен", "free" } },
            { "hud.parking.closed", new[] { "Стоянка для фур: закрыта (улучшение «Стоянка для фур»)", "Truck parking: closed (Truck parking upgrade)" } },
            { "hud.parking", new[] { "Стоянка для фур: {0}/{1} мест занято", "Truck parking: {0}/{1} spots taken" } },
            { "hud.tires", new[] { "Шиномонтаж: {0}", "Tire service: {0}" } },
            { "hud.tires.closed", new[] { "закрыт (улучшение «Шиномонтаж»)", "closed (Tire service upgrade)" } },
            { "hud.tires.working", new[] { "меняем шины, ещё {0:0} с", "changing tires, {0:0} s left" } },
            { "hud.tires.waiting", new[] { "МАШИНА ЖДЁТ — E у бокса", "CAR WAITING — E at the bay" } },
            { "hud.motel.closed", new[] { "Мотель: закрыт (улучшение «Мотель»)", "Motel: closed (Motel upgrade)" } },
            { "hud.motel", new[] { "Мотель: {0}/{1} номеров занято", "Motel: {0}/{1} rooms taken" } },
            { "hud.motel.dirty", new[] { ", грязных {0} — E у ресепшена", ", {0} dirty — E at reception" } },
            { "hud.restroom.disgusting", new[] { "Туалет: ОТВРАТИТЕЛЬНО", "Restroom: DISGUSTING" } },
            { "hud.restroom", new[] { "Туалет: грязь {0:0}%", "Restroom: {0:0}% dirty" } },
            { "hud.pump", new[] { "Колонка {0}: ", "Pump {0}: " } },
            { "hud.pump.locked", new[] { "закрыта (улучшение «Новая колонка»)", "closed (Extra pump upgrade)" } },
            { "hud.pump.broken", new[] { "СЛОМАНА — почините (E рядом)", "BROKEN — repair it (E nearby)" } },
            { "hud.pump.wear", new[] { " [износ {0:0}%]", " [wear {0:0}%]" } },
            { "hud.pump.car", new[] { "{0} {1}, {2} {3:0}/{4:0} л, терпение {5:0}%{6}", "{0} {1}, {2} {3:0}/{4:0} L, patience {5:0}%{6}" } },
            { "carstate.DrivingToPump", new[] { "подъезжает", "arriving" } },
            { "carstate.WaitingForService", new[] { "ждёт заправки", "waiting for fuel" } },
            { "carstate.Fueling", new[] { "заправляется", "fueling" } },
            { "carstate.Shopping", new[] { "водитель в магазине", "driver in the shop" } },
            { "carstate.ReadyToLeave", new[] { "уезжает", "leaving" } },

            // HUD: center
            { "hud.report", new[] {
                "Итоги дня {0}\nДоход: ${1:0}   Расходы: ${2:0}\nПрибыль: ${3:0}\nОбслужено: {4}   Уехали: {5}",
                "Day {0} summary\nIncome: ${1:0}   Expenses: ${2:0}\nProfit: ${3:0}\nServed: {4}   Lost: {5}" } },
            { "hint.CanStartFueling", new[] { "[E / ЛКМ] Заправить", "[E / LMB] Fuel the car" } },
            { "hint.Fueling", new[] { "Идёт заправка...", "Fueling..." } },
            { "hint.CarArriving", new[] { "Машина подъезжает", "Car arriving" } },
            { "hint.Trash", new[] { "[E / ЛКМ] Убрать мусор", "[E / LMB] Pick up litter" } },
            { "hint.Restroom", new[] { "[E / ЛКМ] Убрать туалет", "[E / LMB] Clean the restroom" } },
            { "hint.Tires", new[] { "[E / ЛКМ] Поменять шины", "[E / LMB] Change tires" } },
            { "hint.MotelRoom", new[] { "[E / ЛКМ] Убрать номер в мотеле", "[E / LMB] Clean a motel room" } },
            { "hint.Repair", new[] { "[E / ЛКМ] Чинить колонку (${0:0} за шаг)", "[E / LMB] Repair the pump (${0:0} per step)" } },

            // HUD: panels
            { "panel.upgrades", new[] { "УЛУЧШЕНИЯ, стр. {0}/{1} (цифра — купить, Tab — дальше / закрыть)", "UPGRADES, page {0}/{1} (digit — buy, Tab — next / close)" } },
            { "panel.upgrades.line", new[] { "{0}. {1} [{2}/{3}] — {4}: {5}", "{0}. {1} [{2}/{3}] — {4}: {5}" } },
            { "panel.max", new[] { "макс.", "max" } },
            { "panel.needLevel", new[] { "нужен уровень {0}", "needs level {0}" } },
            { "panel.price", new[] { "${0:0}", "${0:0}" } },
            { "panel.staff", new[] { "ПЕРСОНАЛ {0}/{1} (1–3 — нанять, 4–9 ×2 — уволить, H — закрыть)", "STAFF {0}/{1} (1–3 — hire, 4–9 ×2 — fire, H — close)" } },
            { "panel.staff.candidates", new[] { "Кандидаты сегодня:", "Today's applicants:" } },
            { "panel.staff.candidate", new[] { "{0}. {1}, {2} ({3}), навык {4:0.00}, ${5:0}/день, {6}; найм ${7:0}", "{0}. {1}, {2} ({3}), skill {4:0.00}, ${5:0}/day, {6}; hiring ${7:0}" } },
            { "panel.staff.none", new[] { "Сотрудников пока нет.", "No employees yet." } },
            { "panel.staff.working", new[] { "Работают:", "Employed:" } },
            { "panel.staff.worker", new[] { "{0}. {1}, {2}, навык {3:0.00}, ${4:0}/день, стаж {5} дн.", "{0}. {1}, {2}, skill {3:0.00}, ${4:0}/day, {5} days" } },
            { "panel.staff.confirmFire", new[] { "Нажмите {0} ещё раз, чтобы уволить: {1}", "Press {0} again to fire {1}" } },
            { "panel.paint", new[] { "ПОКРАСКА (цифра — перекрасить, C — закрыть)", "PAINT (digit — repaint, C — close)" } },
            { "panel.paint.current", new[] { "Сейчас: «{0}», клиентов {1:+0;-0;0}%", "Now: \"{0}\", customers {1:+0;-0;0}%" } },
            { "panel.paint.line", new[] { "{0}. «{1}» — {2}, клиентов {3:+0;-0;0}%", "{0}. \"{1}\" — {2}, customers {3:+0;-0;0}%" } },
            { "panel.paint.current.short", new[] { "уже так", "current" } },
            { "panel.store", new[] { "МАГАЗИН (1–5 — товар, +/- — цена, O — заказать {0} шт., M — закрыть)", "SHOP (1–5 — item, +/- — price, O — order {0}, M — close)" } },
            { "panel.store.inside", new[] { "Покупателей внутри: {0}", "Shoppers inside: {0}" } },
            { "panel.store.line", new[] { "{0}. {1}: {2}/{3}   ${4:0.00} (закупка ${5:0.00}, обычно ${6:0.00})", "{0}. {1}: {2}/{3}   ${4:0.00} (cost ${5:0.00}, usual ${6:0.00})" } },
            { "panel.store.pending", new[] { "   +{0} в пути", "   +{0} on the way" } },

            // Notifications
            { "msg.confirmNewGame", new[] { "Нажмите F10 ещё раз, чтобы начать заново", "Press F10 again to start over" } },
            { "msg.language", new[] { "Язык: русский", "Language: English" } },
            { "msg.customerAngry", new[] { "Клиент уехал недовольным", "A customer left unhappy" } },
            { "msg.fuelRanOut", new[] { "Закончилось топливо: {0}! Закажите бензовоз (O)", "Out of {0}! Order a fuel truck (O)" } },
            { "msg.fuelDelivered", new[] { "Бензовоз привёз {0:0} л {1}", "The fuel truck delivered {0:0} L of {1}" } },
            { "msg.pumpBroken", new[] { "Колонка {0:0} сломалась! Почините её (E)", "Pump {0:0} broke down! Repair it (E)" } },
            { "msg.pumpRepaired", new[] { "Колонка {0:0} как новая", "Pump {0:0} is as good as new" } },
            { "msg.noMoney", new[] { "Не хватает денег: нужно ${0:0}", "Not enough money: ${0:0} needed" } },
            { "msg.levelUp", new[] { "Уровень станции {0:0}! Открыты новые улучшения и клиенты", "Station level {0:0}! New upgrades and customers unlocked" } },
            { "msg.tip", new[] { "Чаевые: ${0:0}", "Tip: ${0:0}" } },
            { "msg.fuelStolen", new[] { "Вор уехал без оплаты! Потеряно ${0:0}", "A thief drove off without paying! Lost ${0:0}" } },
            { "msg.thiefCaught", new[] { "Вор пойман и заплатил!", "Thief caught — he paid!" } },
            { "msg.market", new[] { "Цены на нефть: {0:+0.0;-0.0;0}%. Проверьте свои цены", "Oil prices: {0:+0.0;-0.0;0}%. Check your prices" } },
            { "msg.vandals", new[] { "Ночью приходили вандалы и намусорили", "Vandals came at night and left a mess" } },
            { "msg.rushHour", new[] { "Час пик: туристы едут толпой!", "Rush hour: tourists are coming!" } },
            { "msg.sandstorm", new[] { "Песчаная буря: клиентов мало, мусора много", "Sandstorm: few customers, lots of litter" } },
            { "msg.inspectionPassed", new[] { "Проверка пройдена! Премия ${0:0}", "Inspection passed! Bonus ${0:0}" } },
            { "msg.inspectionFailed", new[] { "Проверка: грязно! Штраф ${0:0}", "Inspection: dirty! Fine ${0:0}" } },
            { "msg.shopEmpty", new[] { "Покупатель ушёл из магазина ни с чем — закажите товар (M)", "A shopper left empty-handed — order goods (M)" } },
            { "msg.restroomDisgusting", new[] { "Клиент в ужасе от туалета! Уберите его (E у двери)", "A customer is horrified by the restroom! Clean it (E at the door)" } },
            { "msg.workerStole", new[] { "Из кассы пропало ${0:0}. Кто-то из сотрудников нечист на руку…", "${0:0} is missing from the till. Someone on staff is not honest…" } },
            { "msg.truckParked", new[] { "Дальнобойщик встал на ночёвку", "A trucker parked for the night" } },
            { "msg.parkingPaid", new[] { "Дальнобойщик заплатил за ночь: ${0:0}", "A trucker paid for the night: ${0:0}" } },
            { "msg.productsDelivered", new[] { "В магазин привезли товар: {0:0} шт.", "Goods delivered to the shop: {0:0}" } },
            { "msg.motelPaid", new[] { "Гость мотеля заплатил: ${0:0}", "A motel guest paid: ${0:0}" } },
            { "msg.saved", new[] { "Игра сохранена", "Game saved" } },
            { "msg.loaded", new[] { "Игра загружена", "Game loaded" } },
            { "msg.noSave", new[] { "Сохранение не найдено", "No saved game" } },
            { "msg.newGame", new[] { "Новая игра", "New game" } },
            { "msg.continue", new[] { "Продолжаем: день {0}", "Welcome back: day {0}" } },
            { "msg.tankFull", new[] { "Резервуар полон", "The tank is full" } },
            { "msg.fuelOrdered", new[] { "Заказано {0:0} л {1}, привезут через {2:0} с", "Ordered {0:0} L of {1}, arriving in {2:0} s" } },
            { "msg.noShop", new[] { "На станции нет магазина", "There is no shop at the station" } },
            { "msg.shelvesFull", new[] { "{0}: полки заполнены", "{0}: shelves are full" } },
            { "msg.productsOrdered", new[] { "Заказано: {0} × {1}, привезут через {2:0} с", "Ordered {0} × {1}, arriving in {2:0} s" } },
            { "msg.staffFull", new[] { "Штат полон: не больше {0} сотрудников", "Staff is full: at most {0} employees" } },
            { "msg.noMoneyHire", new[] { "Не хватает денег на найм: нужно ${0:0}", "Not enough money to hire: ${0:0} needed" } },
            { "msg.hired", new[] { "Нанят {0}: {1}", "Hired {0}: {1}" } },
            { "msg.fired", new[] { "Уволен {0}: {1}", "Fired {0}: {1}" } },
            { "msg.alreadyPainted", new[] { "Станция уже так покрашена", "The station already has this paint" } },
            { "msg.schemeNeedsLevel", new[] { "«{0}»: нужен уровень станции {1}", "\"{0}\": needs station level {1}" } },
            { "msg.painted", new[] { "Станция перекрашена: «{0}»", "Station repainted: \"{0}\"" } },
            { "msg.upgradeMax", new[] { "{0}: максимальный уровень", "{0}: maximum level" } },
            { "msg.upgradeNeedsLevel", new[] { "{0}: нужен уровень станции {1}", "{0}: needs station level {1}" } },
            { "msg.upgradeBought", new[] { "Куплено: {0}, уровень {1}", "Bought: {0}, level {1}" } },

            // Achievements
            { "achievement.FirstCustomer.name", new[] { "Первый клиент", "First customer" } },
            { "achievement.FirstCustomer.desc", new[] { "Обслужи первого клиента", "Serve your first customer" } },
            { "achievement.Served100.name", new[] { "Сотня", "A hundred" } },
            { "achievement.Served100.desc", new[] { "Обслужи 100 клиентов", "Serve 100 customers" } },
            { "achievement.Served1000.name", new[] { "Тысяча машин", "A thousand cars" } },
            { "achievement.Served1000.desc", new[] { "Обслужи 1000 клиентов", "Serve 1000 customers" } },
            { "achievement.Trash100.name", new[] { "Дворник", "Street sweeper" } },
            { "achievement.Trash100.desc", new[] { "Собери 100 кусков мусора", "Pick up 100 pieces of litter" } },
            { "achievement.Trash1000.name", new[] { "Чистюля", "Neat freak" } },
            { "achievement.Trash1000.desc", new[] { "Собери 1000 кусков мусора", "Pick up 1000 pieces of litter" } },
            { "achievement.Income10K.name", new[] { "Первые $10 000", "First $10,000" } },
            { "achievement.Income10K.desc", new[] { "Заработай $10 000 на клиентах", "Earn $10,000 from customers" } },
            { "achievement.Income100K.name", new[] { "Нефтяной магнат", "Oil baron" } },
            { "achievement.Income100K.desc", new[] { "Заработай $100 000 на клиентах", "Earn $100,000 from customers" } },
            { "achievement.Level5.name", new[] { "Известное место", "Known place" } },
            { "achievement.Level5.desc", new[] { "Достигни 5-го уровня станции", "Reach station level 5" } },
            { "achievement.Level10.name", new[] { "Легенда трассы", "Highway legend" } },
            { "achievement.Level10.desc", new[] { "Достигни 10-го уровня станции", "Reach station level 10" } },
            { "achievement.ThiefCaught.name", new[] { "Шериф", "Sheriff" } },
            { "achievement.ThiefCaught.desc", new[] { "Поймай вора", "Catch a thief" } },
            { "achievement.MotelGuests10.name", new[] { "Гостеприимство", "Hospitality" } },
            { "achievement.MotelGuests10.desc", new[] { "Прими 10 гостей в мотеле", "Host 10 motel guests" } },
            { "achievement.Truckers10.name", new[] { "Друг дальнобойщиков", "Truckers' friend" } },
            { "achievement.Truckers10.desc", new[] { "Прими 10 дальнобойщиков на ночь", "Host 10 truckers overnight" } },
            { "achievement.CarsWashed50.name", new[] { "Блеск", "Shine" } },
            { "achievement.CarsWashed50.desc", new[] { "Помой 50 машин", "Wash 50 cars" } },
            { "achievement.Tires25.name", new[] { "Шинный мастер", "Tire master" } },
            { "achievement.Tires25.desc", new[] { "Поменяй шины 25 раз", "Change tires 25 times" } },
            { "achievement.PerfectDay.name", new[] { "Идеальный день", "Perfect day" } },
            { "achievement.PerfectDay.desc", new[] { "Обслужи за день 20+ клиентов, и чтобы никто не уехал недовольным", "Serve 20+ customers in a day with nobody leaving unhappy" } },
            { "achievement.Tycoon.name", new[] { "Магнат", "Tycoon" } },
            { "achievement.Tycoon.desc", new[] { "Накопи $50 000", "Save up $50,000" } },
            { "achievement.Spotless.name", new[] { "Ни соринки", "Spotless" } },
            { "achievement.Spotless.desc", new[] { "Доведи чистоту станции до 100%", "Get station cleanliness to 100%" } },
            { "achievement.FullStaff.name", new[] { "Полный штат", "Full staff" } },
            { "achievement.FullStaff.desc", new[] { "Найми 6 сотрудников", "Hire 6 employees" } },
            { "panel.achievements", new[] { "ДОСТИЖЕНИЯ {0}/{1} (J — закрыть)", "ACHIEVEMENTS {0}/{1} (J — close)" } },
            { "panel.achievements.line", new[] { "[{0}] {1} — {2}", "[{0}] {1} — {2}" } },
            { "panel.achievements.stats", new[] { "Дней: {0}   клиентов: {1}   заработано: ${2:0}", "Days: {0}   customers: {1}   earned: ${2:0}" } },
            { "msg.achievement", new[] { "Достижение получено: {0}!", "Achievement unlocked: {0}!" } },
            { "meter.reputation", new[] { "Репутация", "Reputation" } },
            { "meter.cleanliness", new[] { "Чистота", "Cleanliness" } },
            { "meter.experience", new[] { "Опыт", "Experience" } },

            // Menus and settings
            // Renovation and construction
            { "renovation.Windows", new[] { "заколоченные окна", "boarded-up windows" } },
            { "renovation.Graffiti", new[] { "граффити на стенах", "graffiti on the walls" } },
            { "renovation.Fence", new[] { "дырявый забор", "broken fence" } },
            { "renovation.Lamps", new[] { "старые фонари", "old lamps" } },
            { "renovation.VendingMachine", new[] { "ржавый автомат с напитками", "rusty vending machine" } },
            { "renovation.Sign", new[] { "покосившаяся вывеска", "crooked sign" } },
            { "hint.Renovate", new[] { "[E / ЛКМ] Отремонтировать: {0} (${1:0}, уровень {2})", "[E / LMB] Renovate: {0} (${1:0}, level {2})" } },
            { "msg.renovated", new[] { "Отремонтировано: {0}. Станция выглядит лучше!", "Renovated: {0}. The station looks better!" } },
            { "msg.renovationNeedsLevel", new[] { "Для этого ремонта нужен уровень станции {0:0}", "This renovation needs station level {0:0}" } },
            { "quest.title.22", new[] { "Первый ремонт", "First repairs" } },
            { "quest.title.23", new[] { "Новая жизнь", "A new life" } },
            { "quest.goal.Renovate", new[] { "Отремонтируй станцию (E у разбитых окон, забора, вывески…): {0}/{1:0}", "Renovate the station (E at broken windows, fence, sign…): {0}/{1:0}" } },
            { "achievement.FullyRenovated.name", new[] { "Как новая", "Good as new" } },
            { "achievement.FullyRenovated.desc", new[] { "Отремонтируй на станции всё", "Renovate everything at the station" } },
            { "msg.tankerArrived", new[] { "Бензовоз приехал и сливает топливо", "The fuel tanker arrived and is unloading" } },
            { "msg.cargoArrived", new[] { "Грузовик с товаром разгружается у магазина", "The goods truck is unloading at the shop" } },
            { "menu.next", new[] { "Далее", "Next" } },
            { "menu.skip", new[] { "Пропустить", "Skip" } },
            { "menu.start", new[] { "За работу!", "Let's go!" } },
            { "menu.tutorial", new[] { "Обучение", "Tutorial" } },
            { "tutorial.page", new[] { "Страница {0} из {1}", "Page {0} of {1}" } },
            { "tutorial.0.title", new[] { "Добро пожаловать на трассу", "Welcome to the highway" } },
            { "tutorial.0.text", new[] {
                "Ты купил заброшенную заправку посреди пустыни. Колонки сломаны, окна заколочены, повсюду мусор, а денег почти нет.\n\nЗадача — вернуть станции жизнь: навести порядок, обслуживать проезжающих и вложить заработанное в ремонт и новые постройки.",
                "You bought an abandoned gas station in the middle of the desert. The pumps are broken, the windows are boarded up, there is litter everywhere and hardly any money.\n\nYour job is to bring the station back to life: clean up, serve passing drivers and invest the money in repairs and new buildings." } },
            { "tutorial.1.title", new[] { "Как играть", "How to play" } },
            { "tutorial.1.text", new[] {
                "Ходи на WASD. E (или ЛКМ) — действие рядом: заправить ждущую машину, починить колонку, отремонтировать сломанное, убрать туалет, подобрать мусор.\n\nМашины сами встают в очередь. Подойди к колонке, где машина ждёт, и нажми E. Клиент заплатит и уедет — или зайдёт в магазин.",
                "Walk with WASD. E (or LMB) is the nearby action: fuel a waiting car, repair a pump, renovate something broken, clean the restroom, pick up litter.\n\nCars queue up on their own. Walk to a pump where a car is waiting and press E. The customer pays and drives off — or visits the shop." } },
            { "tutorial.2.title", new[] { "Деньги и развитие", "Money and growth" } },
            { "tutorial.2.text", new[] {
                "Следи за запасами топлива (справа сверху) и заказывай бензовоз клавишей O — он приедет и сольёт топливо. Цены меняются клавишами +/−.\n\nTab — улучшения, M — товары магазина, H — найм персонала, C — покраска. Новые здания строятся после покупки улучшения.",
                "Watch the fuel stock (top right) and order a fuel tanker with O — it will drive in and unload. Change prices with +/−.\n\nTab — upgrades, M — shop goods, H — hire staff, C — paint. New buildings are built once you buy their upgrade." } },
            { "tutorial.3.title", new[] { "Задания", "Tasks" } },
            { "tutorial.3.text", new[] {
                "Вверху экрана — текущее задание, а оранжевая стрелка ▼ показывает, куда идти. Задания ведут от уборки мусора к собственному мотелю.\n\nEsc — пауза и настройки, T — ускорить время, J — достижения. Удачи!",
                "The current task is at the top of the screen, and the orange arrow ▼ shows where to go. Tasks lead you from picking up litter to running your own motel.\n\nEsc — pause and settings, T — speed up time, J — achievements. Good luck!" } },
            { "review.5.0", new[] { "Лучшая заправка на трассе!", "Best gas station on the highway!" } },
            { "review.5.1", new[] { "Быстро, чисто, вежливо. Вернусь.", "Fast, clean, friendly. I'll be back." } },
            { "review.5.2", new[] { "Пять звёзд, кофе тоже отличный.", "Five stars, great coffee too." } },
            { "review.4.0", new[] { "Хорошее место, почти без очереди.", "Nice place, hardly any queue." } },
            { "review.4.1", new[] { "Всё нормально, цены терпимые.", "All good, fair prices." } },
            { "review.4.2", new[] { "Приятная остановка в пути.", "A pleasant stop on the road." } },
            { "review.3.0", new[] { "Нормально, но можно лучше.", "Okay, but could be better." } },
            { "review.3.1", new[] { "Пришлось подождать.", "Had to wait a bit." } },
            { "review.3.2", new[] { "Цены кусаются.", "Prices bite." } },
            { "review.2.0", new[] { "Долго и грязновато.", "Slow and a bit dirty." } },
            { "review.2.1", new[] { "Дорого для такого места.", "Expensive for a place like this." } },
            { "review.2.2", new[] { "Не впечатлило.", "Not impressed." } },
            { "review.1.0", new[] { "Ждал вечность и уехал.", "Waited forever and left." } },
            { "review.1.1", new[] { "Ужасное обслуживание!", "Terrible service!" } },
            { "review.1.2", new[] { "Больше сюда ни ногой.", "Never coming back." } },
            { "card.wants", new[] { "{0}{1} · {2:0} л", "{0}{1} · {2:0} L" } },
            { "card.fueling", new[] { "{0}{1} · {2:0}/{3:0} л", "{0}{1} · {2:0}/{3:0} L" } },
            { "card.tires", new[] { "{0}ждёт шины", "{0}waiting for tires" } },
            { "panel.finance", new[] { "ФИНАНСЫ (F — банк)", "FINANCES (F — bank)" } },
            { "panel.finance.today", new[] { "Сегодня: +${0:0} / -${1:0} = ${2:0}", "Today: +${0:0} / -${1:0} = ${2:0}" } },
            { "panel.finance.yesterday", new[] { "Вчера: +${0:0} / -${1:0} = ${2:0}", "Yesterday: +${0:0} / -${1:0} = ${2:0}" } },
            { "panel.finance.week", new[] { "За {0} дн.: +${1:0} / -${2:0} = ${3:0}", "Last {0} days: +${1:0} / -${2:0} = ${3:0}" } },
            { "panel.finance.rating", new[] { "Рейтинг: {0} {1:0.0} ({2} отзывов)", "Rating: {0} {1:0.0} ({2} reviews)" } },
            { "panel.finance.noRating", new[] { "Отзывов пока нет", "No reviews yet" } },
            { "panel.finance.reviews", new[] { "Последние отзывы:", "Latest reviews:" } },
            { "panel.finance.chart", new[] { "Доход (зелёный) и расходы (красный) по дням:", "Income (green) and expenses (red) per day:" } },
            { "panel.finance.noHistory", new[] { "График появится после первого дня.", "The chart appears after the first day." } },
            { "upgrade.name.Decor", new[] { "Декор", "Decorations" } },
            { "upgrade.desc.Decor", new[] { "флаги, цветы, скамейки и гирлянды: +3% клиентов за уровень", "flags, flowers, benches and string lights: +3% customers per level" } },
            { "station.defaultName", new[] { "Оазис", "Oasis" } },
            { "menu.stationName", new[] { "Название станции", "Station name" } },
            { "menu.stationName.hint", new[] { "Название появится на вывеске у дороги. Оставь поле пустым, чтобы вернуть стандартное.", "The name appears on the roadside sign. Leave it empty to use the default." } },
            { "menu.saveName", new[] { "Сохранить", "Save" } },
            { "settings.musicVolume", new[] { "Музыка (радио)", "Music (radio)" } },
            { "settings.radio", new[] { "Радиостанция", "Radio station" } },
            { "radio.Off", new[] { "выключено", "off" } },
            { "radio.Country", new[] { "Route 66 FM — кантри", "Route 66 FM — country" } },
            { "radio.Synthwave", new[] { "Neon Drive — синтвейв", "Neon Drive — synthwave" } },
            { "radio.LoFi", new[] { "Desert Chill — лоу-фай", "Desert Chill — lo-fi" } },
            { "msg.radio", new[] { "Радио: {0}", "Radio: {0}" } },
            { "hud.speed", new[] { "   ×{0}", "   ×{0}" } },
            { "menu.title", new[] { "GAS STATION", "GAS STATION" } },
            { "menu.subtitle", new[] { "Симулятор заправки у трассы", "Roadside gas station simulator" } },
            { "menu.play", new[] { "Играть", "Play" } },
            { "menu.continue", new[] { "Продолжить", "Continue" } },
            { "menu.newGame", new[] { "Новая игра", "New game" } },
            { "menu.settings", new[] { "Настройки", "Settings" } },
            { "menu.controls", new[] { "Управление", "Controls" } },
            { "menu.quit", new[] { "Выйти из игры", "Quit game" } },
            { "menu.version", new[] { "Версия {0}", "Version {0}" } },
            { "menu.pause", new[] { "Пауза", "Paused" } },
            { "menu.resume", new[] { "Продолжить", "Resume" } },
            { "menu.save", new[] { "Сохранить", "Save" } },
            { "menu.load", new[] { "Загрузить", "Load" } },
            { "menu.toMainMenu", new[] { "В главное меню", "Main menu" } },
            { "menu.back", new[] { "Назад", "Back" } },
            { "menu.yes", new[] { "Да", "Yes" } },
            { "menu.no", new[] { "Нет", "No" } },
            { "menu.confirm.newGame", new[] { "Начать новую игру? Текущее сохранение будет удалено.", "Start a new game? The current save will be deleted." } },
            { "menu.confirm.load", new[] { "Загрузить последнее сохранение? Несохранённый прогресс пропадёт.", "Load the last save? Unsaved progress will be lost." } },
            { "settings.display", new[] { "ЭКРАН", "DISPLAY" } },
            { "settings.resolution", new[] { "Разрешение", "Resolution" } },
            { "settings.mode", new[] { "Режим экрана", "Screen mode" } },
            { "settings.mode.ExclusiveFullScreen", new[] { "Полный экран", "Fullscreen" } },
            { "settings.mode.FullScreenWindow", new[] { "Окно без рамки", "Borderless window" } },
            { "settings.mode.Windowed", new[] { "В окне", "Windowed" } },
            { "settings.vsync", new[] { "Вертикальная синхронизация", "V-Sync" } },
            { "settings.fps", new[] { "Ограничение FPS (без V-Sync)", "Frame rate limit (without V-Sync)" } },
            { "settings.fps.unlimited", new[] { "Без ограничения", "Unlimited" } },
            { "settings.graphics", new[] { "ГРАФИКА", "GRAPHICS" } },
            { "settings.quality", new[] { "Качество", "Quality" } },
            { "settings.renderScale", new[] { "Масштаб рендера", "Render scale" } },
            { "settings.audio", new[] { "ЗВУК", "AUDIO" } },
            { "settings.masterVolume", new[] { "Общая громкость", "Master volume" } },
            { "settings.effectsVolume", new[] { "Звуковые эффекты", "Sound effects" } },
            { "settings.interface", new[] { "ИНТЕРФЕЙС", "INTERFACE" } },
            { "settings.language", new[] { "Язык", "Language" } },
            { "settings.uiScale", new[] { "Размер интерфейса", "UI scale" } },
            { "settings.showControls", new[] { "Подсказки по клавишам", "Key hints" } },
            { "settings.game", new[] { "ИГРА", "GAME" } },
            { "settings.gameSpeed", new[] { "Скорость игры", "Game speed" } },
            { "settings.autosave", new[] { "Автосохранение в конце дня", "Autosave at the end of each day" } },
            { "controls.text", new[] {
                "WASD / стрелки — ходить\nE / ЛКМ — действие рядом: заправить машину, поменять шины, починить колонку, убрать туалет или номер мотеля, подобрать мусор\n\n1 / 2 / 3 — выбрать топливо   + / − — цена   O — заказать 500 л\nTab — улучшения (две страницы)   M — магазин   C — покраска   H — персонал   J — достижения   K — постоянные клиенты   F — финансы, банк, конкурент\nНоутбук у двери магазина (E рядом или N откуда угодно): почта с контрактами, банк, конкурент, клиенты, статистика — всё мышью\nB — режим строительства: WASD — камера, колесо — масштаб, 1–8 — объект, Q / E — поворот, ЛКМ — поставить, ПКМ — убрать\n\nT — скорость игры ×1 / ×2 / ×3   R — радио   F1 — подсказки   L — язык\nF5 — сохранить   F9 — загрузить   Esc — пауза",
                "WASD / arrows — walk\nE / LMB — nearby action: fuel a car, change tires, repair a pump, clean the restroom or a motel room, pick up litter\n\n1 / 2 / 3 — select fuel   + / − — price   O — order 500 L\nTab — upgrades (two pages)   M — shop   C — paint   H — staff   J — achievements   K — regulars   F — finances, bank, competitor\nThe laptop by the shop door (E next to it or N anywhere): contract mail, bank, competitor, regulars, statistics — all with the mouse\nB — build mode: WASD — camera, wheel — zoom, 1–8 — object, Q / E — rotate, LMB — place, RMB — remove\n\nT — game speed ×1 / ×2 / ×3   R — radio   F1 — hints   L — language\nF5 — save   F9 — load   Esc — pause" } },

            // Bank, bills and the competitor
            { "msg.loanAlready", new[] { "Сначала погаси текущий кредит", "Repay the current loan first" } },
            { "msg.loanTaken", new[] { "Кредит ${0:0} получен. Платёж ${1:0} в неделю, {2} недель", "Loan of ${0:0} received. ${1:0} a week for {2} weeks" } },
            { "msg.noLoan", new[] { "Кредита нет", "No loan to repay" } },
            { "msg.loanRepaid", new[] { "Кредит погашен досрочно за ${0:0}", "Loan repaid early for ${0:0}" } },
            { "msg.loanPaidOff", new[] { "Последний платёж по кредиту — долг закрыт!", "Last loan payment made — the debt is cleared!" } },
            { "msg.insuranceOn", new[] { "Страховка оформлена: ${0:0} в неделю", "Insurance taken out: ${0:0} a week" } },
            { "msg.insuranceOff", new[] { "Страховка отменена", "Insurance cancelled" } },
            { "msg.insurancePayout", new[] { "Страховая возместила ${0:0}", "Insurance paid out ${0:0}" } },
            { "msg.weeklyBills", new[] { "Неделя закрыта: налог и платежи — ${0:0}", "Week closed: tax and payments — ${0:0}" } },
            { "msg.bankruptcyWarning", new[] { "Станция в минусе! До банкротства дней: {0}", "The station is in the red! Days until bankruptcy: {0}" } },
            { "msg.buyoutNeedsLevel", new[] { "Выкупить конкурента можно с уровня {0}", "You can buy out the competitor from level {0}" } },
            { "msg.competitorOpened", new[] { "Через дорогу открылась заправка PetroMax!", "A PetroMax station opened across the road!" } },
            { "msg.competitorPriceCut", new[] { "PetroMax снизил цены", "PetroMax cut its prices" } },
            { "msg.competitorPriceRise", new[] { "PetroMax поднял цены", "PetroMax raised its prices" } },
            { "msg.competitorPromo.Discount", new[] { "PetroMax устроил распродажу: −10% на топливо", "PetroMax is running a sale: −10% on fuel" } },
            { "msg.competitorPromo.Advertising", new[] { "PetroMax запустил рекламу на трассе", "PetroMax launched a highway ad campaign" } },
            { "msg.competitorBoughtOut", new[] { "PetroMax теперь твой! Все клиенты трассы едут к тебе", "PetroMax is yours now! Every driver on the road comes to you" } },
            { "difficulty.Relaxed", new[] { "Спокойная", "Relaxed" } },
            { "difficulty.Normal", new[] { "Обычная", "Normal" } },
            { "difficulty.Survival", new[] { "Выживание", "Survival" } },
            { "difficulty.Relaxed.text", new[] { "Счета вдвое меньше, банкротства нет.", "Half bills, no bankruptcy." } },
            { "difficulty.Normal.text", new[] { "Обычные счета. 7 дней в минусе — банкротство.", "Normal bills. 7 days in the red means bankruptcy." } },
            { "difficulty.Survival.text", new[] { "Счета в полтора раза выше. 4 дня в минусе — конец игры.", "Bills are 50% higher. 4 days in the red and the game is over." } },
            { "panel.bank", new[] { "БАНК — сложность: {0} (F — конкурент)", "BANK — difficulty: {0} (F — competitor)" } },
            { "panel.bank.noLoan", new[] { "Кредита нет. Предложения банка:", "No loan. The bank offers:" } },
            { "panel.bank.offer", new[] { "{0}. ${1:0} под {2:0}% на {3} нед. — ${4:0} в неделю", "{0}. ${1:0} at {2:0}% for {3} weeks — ${4:0} a week" } },
            { "panel.bank.loan", new[] { "Долг по кредиту: ${0:0}, платёж ${1:0} в неделю", "Loan balance: ${0:0}, ${1:0} a week" } },
            { "panel.bank.repay", new[] { "3. Погасить досрочно за ${0:0}", "3. Repay early for ${0:0}" } },
            { "panel.bank.insured", new[] { "4. Страховка: ЕСТЬ (${0:0}/нед., покрывает {1:0}% краж)", "4. Insurance: ON (${0:0}/week, covers {1:0}% of thefts)" } },
            { "panel.bank.notInsured", new[] { "4. Страховка: нет (${0:0}/нед., покрывает {1:0}% краж)", "4. Insurance: OFF (${0:0}/week, covers {1:0}% of thefts)" } },
            { "panel.bank.utilities", new[] { "Свет и вода за прошлую ночь: ${0:0}", "Power and water last night: ${0:0}" } },
            { "panel.bank.tax", new[] { "Налог {0:0}% с выручки: за неделю ${1:0} → ${2:0}, через {3} дн.", "Tax {0:0}% of revenue: ${1:0} this week → ${2:0}, due in {3} days" } },
            { "panel.bank.debt", new[] { "В минусе дней: {0} из {1}!", "Days in the red: {0} of {1}!" } },
            { "panel.bank.debtRelaxed", new[] { "В минусе дней: {0}", "Days in the red: {0}" } },
            { "panel.bank.help", new[] { "1 / 2 — взять кредит   3 — погасить   4 — страховка", "1 / 2 — take a loan   3 — repay   4 — insurance" } },
            { "panel.rival", new[] { "КОНКУРЕНТ — PetroMax (F — закрыть)", "COMPETITOR — PetroMax (F — close)" } },
            { "panel.rival.notOpen", new[] { "Участок напротив пока пуст. Стройка закончится к дню {0}.", "The lot across the road is still empty. Construction ends by day {0}." } },
            { "panel.rival.boughtOut", new[] { "Станция напротив теперь часть «{0}». Конкурентов на трассе нет.", "The station across the road is part of \"{0}\" now. No competition on this road." } },
            { "panel.rival.header", new[] { "Топливо      мы     они", "Fuel         us     them" } },
            { "panel.rival.reputation", new[] { "Репутация: мы {0:0}%, они {1:0}%", "Reputation: us {0:0}%, them {1:0}%" } },
            { "panel.rival.promo.Discount", new[] { "У них распродажа, дней осталось: {0}", "They are running a sale, days left: {0}" } },
            { "panel.rival.promo.Advertising", new[] { "У них реклама на трассе, дней осталось: {0}", "They are advertising on the road, days left: {0}" } },
            { "panel.rival.share", new[] { "Наша доля водителей: {0:0}%", "Our share of drivers: {0:0}%" } },
            { "panel.rival.buyout", new[] { "1 — выкупить PetroMax за ${0:0}", "1 — buy out PetroMax for ${0:0}" } },
            { "panel.rival.buyoutLocked", new[] { "Выкуп за ${0:0} откроется на уровне {1}", "Buyout for ${0:0} unlocks at level {1}" } },
            { "panel.rival.confirmBuyout", new[] { "Выкупить PetroMax за ${0:0}? Нажми 1 ещё раз", "Buy out PetroMax for ${0:0}? Press 1 again" } },
            { "menu.difficulty", new[] { "Выбери сложность", "Choose difficulty" } },
            { "menu.gameOver", new[] { "Банкротство", "Bankrupt" } },
            { "menu.gameOver.text", new[] { "Банк забрал «{0}» за долги на {1}-й день.\nОбслужено клиентов: {2}. Уровень станции: {3}.", "The bank took \"{0}\" for its debts on day {1}.\nCustomers served: {2}. Station level: {3}." } },

            // Build mode
            { "prop.name.TrashBin", new[] { "Урна", "Trash bin" } },
            { "prop.name.Bench", new[] { "Скамейка", "Bench" } },
            { "prop.name.Planter", new[] { "Клумба", "Planter" } },
            { "prop.name.Lamp", new[] { "Фонарь", "Lamp" } },
            { "prop.name.RoadSign", new[] { "Указатель", "Road sign" } },
            { "prop.name.AirPump", new[] { "Подкачка шин", "Air pump" } },
            { "prop.name.WaterMachine", new[] { "Автомат с водой", "Water machine" } },
            { "prop.name.SecurityCamera", new[] { "Камера", "Security camera" } },
            { "prop.desc.TrashBin", new[] { "Клиенты рядом (6 м) мусорят на 70% меньше.", "Customers nearby (6 m) litter 70% less." } },
            { "prop.desc.Bench", new[] { "Ждать приятнее: +4% терпения клиентов (до 5 скамеек).", "Waiting is easier: +4% customer patience (up to 5 benches)." } },
            { "prop.desc.Planter", new[] { "Станция красивее: +2% трафика (до 10 клумб).", "A nicer station: +2% traffic (up to 10 planters)." } },
            { "prop.desc.Lamp", new[] { "Светит ночью, отпугивает вандалов и воров.", "Lights up the night, scares off vandals and thieves." } },
            { "prop.desc.RoadSign", new[] { "Водители замечают станцию: +6% трафика (до 3 указателей).", "Drivers notice the station: +6% traffic (up to 3 signs)." } },
            { "prop.desc.AirPump", new[] { "Клиенты подкачивают шины: немного денег и репутации.", "Customers pump up their tires: a little money and reputation." } },
            { "prop.desc.WaterMachine", new[] { "Клиенты покупают воду: $3 то тут, то там.", "Customers buy water: $3 every now and then." } },
            { "prop.desc.SecurityCamera", new[] { "Воры у колонок в радиусе 12 м попадаются чаще.", "Thieves at pumps within 12 m get caught more often." } },
            { "build.error.OutsideLot", new[] { "Здесь уже не наш участок", "This is outside our lot" } },
            { "build.error.Blocked", new[] { "Здесь ездят машины или стоит здание", "Cars drive here or a building stands here" } },
            { "build.error.TooClose", new[] { "Слишком близко к другому объекту", "Too close to another object" } },
            { "build.error.TooMany", new[] { "Больше объектов не поместится", "No room for more objects" } },
            { "msg.propPlaced", new[] { "Поставлено: {0}", "Placed: {0}" } },
            { "msg.propRemoved", new[] { "Убрано: {0}, возврат ${1:0}", "Removed: {0}, refund ${1:0}" } },
            { "msg.propNeedsLevel", new[] { "{0} откроется на уровне {1}", "{0} unlocks at level {1}" } },
            { "panel.build", new[] { "СТРОЙКА — объектов {0} из {1} (B — выйти)", "BUILD — {0} of {1} objects (B — exit)" } },
            { "panel.build.item", new[] { "{0}. {1} — ${2:0} (стоит: {3})", "{0}. {1} — ${2:0} (placed: {3})" } },
            { "panel.build.locked", new[] { "{0}. {1} — с уровня {2}", "{0}. {1} — from level {2}" } },
            { "panel.build.help", new[] { "ЛКМ — поставить   ПКМ — убрать (половина цены назад)   Q / E — поворот   колесо — масштаб", "LMB — place   RMB — remove (half the price back)   Q / E — rotate   wheel — zoom" } },

            // Regulars
            { "regular.0.name", new[] { "Боб", "Bob" } },
            { "regular.0.about", new[] { "дальнобойщик, любит дизель и кофе", "trucker, loves diesel and coffee" } },
            { "regular.0.line.0", new[] { "Как обычно, дизель до полного. И кофе покрепче!", "The usual: diesel, fill her up. And strong coffee!" } },
            { "regular.0.line.1", new[] { "Семьсот миль позади, триста впереди. Жизнь!", "Seven hundred miles behind, three hundred ahead. That's life!" } },
            { "regular.1.name", new[] { "Марина", "Marina" } },
            { "regular.1.about", new[] { "таксистка, заезжает почти каждый день", "taxi driver, drops in almost every day" } },
            { "regular.1.line.0", new[] { "Быстренько, у меня клиент в аэропорт!", "Quick one, I've got a fare to the airport!" } },
            { "regular.1.line.1", new[] { "Опять весь город перекопали, только у вас спокойно.", "They dug up the whole town again, only here it's quiet." } },
            { "regular.2.name", new[] { "Семья Ивановых", "The Ivanov family" } },
            { "regular.2.about", new[] { "едут на выходные к морю", "driving to the seaside for the weekend" } },
            { "regular.2.line.0", new[] { "Дети, в туалет и обратно, быстро!", "Kids, restroom and back, quick!" } },
            { "regular.2.line.1", new[] { "Помоем машину — и дальше, отпуск ждёт!", "A car wash and we're off, the holiday awaits!" } },
            { "regular.3.name", new[] { "Байкер Гарри", "Harry the biker" } },
            { "regular.3.about", new[] { "гоняет по пятницам и субботам", "rides on Fridays and Saturdays" } },
            { "regular.3.line.0", new[] { "Полный бак девяносто пятого для моей красотки.", "Fill up my beauty with 95." } },
            { "regular.3.line.1", new[] { "Слышал про слёт в пустыне? Будет громко!", "Heard about the desert rally? It's going to be loud!" } },
            { "regular.4.name", new[] { "Дед Петя", "Old Pete" } },
            { "regular.4.about", new[] { "пенсионер, заезжает за газетой и кофе", "retiree, comes for the paper and coffee" } },
            { "regular.4.line.0", new[] { "Раньше тут бензин стоил копейки, эх...", "Gas used to cost pennies here, oh well..." } },
            { "regular.4.line.1", new[] { "Кофе у вас лучше, чем в городе, честно.", "Your coffee beats the town's, honest." } },
            { "regular.5.name", new[] { "Лена", "Lena" } },
            { "regular.5.about", new[] { "курьер, всегда торопится", "courier, always in a hurry" } },
            { "regular.5.line.0", new[] { "У меня восемь посылок и полчаса!", "Eight parcels and half an hour!" } },
            { "regular.5.line.1", new[] { "Только не очередь, только не сегодня...", "Not a queue, not today..." } },
            { "regular.6.name", new[] { "Большой Майк", "Big Mike" } },
            { "regular.6.about", new[] { "ночной дальнобойщик", "night trucker" } },
            { "regular.6.line.0", new[] { "Ночью на трассе только я да койоты.", "At night it's just me and the coyotes out here." } },
            { "regular.6.line.1", new[] { "Дизель, пончик и десять минут тишины.", "Diesel, a donut and ten minutes of quiet." } },
            { "regular.7.name", new[] { "Доктор Картер", "Dr. Carter" } },
            { "regular.7.about", new[] { "врач, по утрам едет в больницу", "doctor, drives to the hospital in the mornings" } },
            { "regular.7.line.0", new[] { "Смена через сорок минут, выручайте.", "My shift starts in forty minutes, help me out." } },
            { "regular.7.line.1", new[] { "Чистый туалет на заправке — это медицина!", "A clean restroom is public health!" } },
            { "regular.8.name", new[] { "Шериф Доусон", "Sheriff Dawson" } },
            { "regular.8.about", new[] { "следит за порядком на трассе", "keeps the highway in order" } },
            { "regular.8.line.0", new[] { "Всё спокойно? Воров не видели?", "All quiet? Seen any thieves?" } },
            { "regular.8.line.1", new[] { "Хорошая заправка — меньше работы полиции.", "A good station means less work for the police." } },
            { "regular.9.name", new[] { "Фермер Роза", "Rosa the farmer" } },
            { "regular.9.about", new[] { "везёт урожай на рынок", "takes her crops to the market" } },
            { "regular.9.line.0", new[] { "Пикап полный арбузов, а бак пустой!", "The pickup's full of melons and the tank is empty!" } },
            { "regular.9.line.1", new[] { "Засуха в этом году, но мы держимся.", "Dry year, but we're hanging on." } },
            { "regular.10.name", new[] { "Коммивояжёр Тони", "Tony the salesman" } },
            { "regular.10.about", new[] { "продаёт пылесосы по всему штату", "sells vacuum cleaners all over the state" } },
            { "regular.10.line.0", new[] { "Кстати, пылесос вам не нужен? Шучу!", "Need a vacuum cleaner, by the way? Kidding!" } },
            { "regular.10.line.1", new[] { "Ещё три города до вечера. Кофе, пожалуйста!", "Three more towns before dark. Coffee, please!" } },
            { "regular.11.name", new[] { "Семья Ким", "The Kim family" } },
            { "regular.11.about", new[] { "воскресные путешественники", "Sunday travellers" } },
            { "regular.11.line.0", new[] { "Какие сувениры у вас есть?", "What souvenirs have you got?" } },
            { "regular.11.line.1", new[] { "Сфотографируемся у вашей вывески!", "Let's take a photo by your sign!" } },
            { "regular.12.name", new[] { "Студент Джейк", "Jake the student" } },
            { "regular.12.about", new[] { "едет домой на выходные", "drives home for the weekend" } },
            { "regular.12.line.0", new[] { "На десять долларов, больше нет...", "Ten dollars' worth, that's all I've got..." } },
            { "regular.12.line.1", new[] { "Чипсы и газировка — ужин чемпиона.", "Chips and soda, the dinner of champions." } },
            { "regular.13.name", new[] { "Бабушка Ольга", "Grandma Olga" } },
            { "regular.13.about", new[] { "едет к внукам по средам", "visits her grandchildren on Wednesdays" } },
            { "regular.13.line.0", new[] { "Внукам конфет возьму, у вас свежие?", "I'll get sweets for the grandkids, are they fresh?" } },
            { "regular.13.line.1", new[] { "Какой вежливый молодой человек!", "What a polite young man!" } },
            { "regular.14.name", new[] { "Механик Сэм", "Sam the mechanic" } },
            { "regular.14.about", new[] { "чинит всё, что ездит", "fixes anything with wheels" } },
            { "regular.14.line.0", new[] { "Колонку не пора смазать? Слышу — скрипит.", "Isn't that pump due for grease? I hear it squeak." } },
            { "regular.14.line.1", new[] { "Помою машину, а то клиенты не поверят, что я механик.", "A wash, or customers won't believe I'm a mechanic." } },
            { "regular.15.name", new[] { "Фотограф Нина", "Nina the photographer" } },
            { "regular.15.about", new[] { "снимает закаты в пустыне", "shoots desert sunsets" } },
            { "regular.15.line.0", new[] { "Свет сегодня волшебный!", "The light is magical today!" } },
            { "regular.15.line.1", new[] { "Ваша заправка на закате — готовая обложка.", "Your station at sunset is a ready-made cover." } },
            { "regular.16.name", new[] { "Виктор", "Viktor" } },
            { "regular.16.about", new[] { "дальнобойщик, ездит в ночь", "long-hauler, drives through the night" } },
            { "regular.16.line.0", new[] { "Три часа ночи — лучшее время для дороги.", "Three a.m. is the best time for the road." } },
            { "regular.16.line.1", new[] { "Дизель, и я исчезаю до следующей недели.", "Diesel, and I'm gone till next week." } },
            { "regular.17.name", new[] { "Шеф Луиджи", "Chef Luigi" } },
            { "regular.17.about", new[] { "возит продукты в свой ресторан", "drives supplies to his restaurant" } },
            { "regular.17.line.0", new[] { "Мамма миа, какой запах бензина! Шучу, полный бак.", "Mamma mia, the smell of gasoline! Kidding, fill it up." } },
            { "regular.17.line.1", new[] { "Приезжайте ко мне на пасту, скажите, что от Луиджи!", "Come for pasta, tell them Luigi sent you!" } },
            { "regular.18.name", new[] { "Группа «Пыльные дьяволы»", "The Dust Devils band" } },
            { "regular.18.about", new[] { "гастролируют на старом фургоне", "tour in an old van" } },
            { "regular.18.line.0", new[] { "Сегодня играем в соседнем городе, приходите!", "We're playing in the next town tonight, come along!" } },
            { "regular.18.line.1", new[] { "Бак полный, струны новые — поехали!", "Full tank, new strings, let's roll!" } },
            { "regular.19.name", new[] { "Мэр Брукс", "Mayor Brooks" } },
            { "regular.19.about", new[] { "глава округа", "the county mayor" } },
            { "regular.19.line.0", new[] { "Хорошая станция — гордость округа.", "A good station is the county's pride." } },
            { "regular.19.line.1", new[] { "Помойте, пожалуйста, у меня встреча.", "A wash, please, I have a meeting." } },
            { "msg.regularMet", new[] { "Новый знакомый: {0} — {1}", "New face: {0}, {1}" } },
            { "msg.regularArrived", new[] { "{0}: «{1}»", "{0}: \"{1}\"" } },
            { "msg.regularLost", new[] { "{0} больше не хочет к нам — теперь заправляется у PetroMax", "{0} is upset and now fills up at PetroMax" } },
            { "msg.regularLostNoRival", new[] { "{0} больше не приезжает: слишком много плохих визитов", "{0} is upset and stopped coming" } },
            { "msg.regularFriend", new[] { "{0} теперь лучший друг станции: чаевые и новые клиенты!", "{0} is now the station's best friend: tips and new customers!" } },
            { "msg.criticPraise", new[] { "В газете вышла хвалебная статья о станции! +10% клиентов на неделю", "A glowing article about the station is out! +10% customers for a week" } },
            { "msg.criticPan", new[] { "Критик разгромил станцию в газете. −10% клиентов на неделю", "A critic panned the station in the paper. −10% customers for a week" } },
            { "msg.special.TourBus", new[] { "Туристический автобус! {0} пассажиров сейчас пойдут в магазин", "A tour bus! {0} passengers are heading for the shop" } },
            { "msg.special.Biker", new[] { "Колонна байкеров: {0} мотоциклов", "A biker convoy: {0} bikes" } },
            { "msg.special.Emergency", new[] { "Спецмашина! Пропусти её без очереди", "Emergency vehicle! Let it skip the queue" } },
            { "msg.special.TowTruck", new[] { "Эвакуатор везёт машину на шиномонтаж", "A tow truck brings a car to the tire service" } },
            { "msg.emergencyServed", new[] { "Спецмашина заправлена вовремя. Репутация растёт", "Emergency vehicle fueled in time. Reputation up" } },
            { "panel.regulars", new[] { "ПОСТОЯННЫЕ КЛИЕНТЫ — знакомы {0} из {1} (K — закрыть)", "REGULARS — met {0} of {1} (K — close)" } },
            { "panel.regulars.praise", new[] { "Хвалебная статья в газете: ещё {0} дн.", "Glowing newspaper article: {0} more days" } },
            { "panel.regulars.pan", new[] { "Разгромная статья в газете: ещё {0} дн.", "Scathing newspaper article: {0} more days" } },
            { "panel.regulars.line", new[] { "{0} — {1}, {2}, ~{3}:00, визитов {4}  {5}", "{0} — {1}, {2}, ~{3}:00, {4} visits  {5}" } },
            { "panel.regulars.lost", new[] { "ушёл к конкуренту", "went to the competitor" } },
            { "panel.regulars.upset", new[] { "обижен ({0} из {1})", "upset ({0} of {1})" } },
            { "panel.regulars.none", new[] { "Пока никого. Постоянные клиенты приезжают в свои дни и часы.", "Nobody yet. Regulars come on their own days and hours." } },
            { "panel.regulars.help", new[] { "Довольные постоянники приезжают чаще, дают чаевые и приводят друзей. Три плохих визита подряд — и они уходят.", "Happy regulars come more often, tip and bring friends. Three bad visits in a row and they leave." } },
            { "weekday.every", new[] { "каждый день", "every day" } },
            { "weekday.weekdays", new[] { "по будням", "weekdays" } },
            { "weekday.weekend", new[] { "по выходным", "weekends" } },
            { "weekday.0", new[] { "пн", "Mon" } },
            { "weekday.1", new[] { "вт", "Tue" } },
            { "weekday.2", new[] { "ср", "Wed" } },
            { "weekday.3", new[] { "чт", "Thu" } },
            { "weekday.4", new[] { "пт", "Fri" } },
            { "weekday.5", new[] { "сб", "Sat" } },
            { "weekday.6", new[] { "вс", "Sun" } },

            // Contracts and the laptop
            { "contract.TaxiFleet.name", new[] { "Таксопарк «Жёлтый койот»", "Yellow Coyote Cabs" } },
            { "contract.TaxiFleet.desc", new[] { "Два такси утром и вечером. Небольшой, но надёжный контракт.", "Two taxis in the morning and in the evening. Small but steady." } },
            { "contract.Police.name", new[] { "Полиция округа", "County police" } },
            { "contract.Police.desc", new[] { "Патрульные машины со скидкой. Пока контракт идёт, воры обходят станцию стороной.", "Patrol cars at a discount. While the contract runs, thieves stay away." } },
            { "contract.Delivery.name", new[] { "Служба доставки «Кактус-Экспресс»", "Cactus Express deliveries" } },
            { "contract.Delivery.desc", new[] { "Фургон каждые два часа днём. Держи колонку свободной!", "A van every two hours during the day. Keep a pump free!" } },
            { "contract.BusCompany.name", new[] { "Автобусы «Пустынная линия»", "Desert Line buses" } },
            { "contract.BusCompany.desc", new[] { "Три автобуса каждое утро в 8:00, много дизеля.", "Three buses every morning at 8:00, lots of diesel." } },
            { "msg.contractsFull", new[] { "Больше {0} контрактов сразу не потянуть", "You can't handle more than {0} contracts at once" } },
            { "msg.contractNeedsLevel", new[] { "Нужен уровень станции {0}", "Requires station level {0}" } },
            { "msg.contractWalkedAway", new[] { "Контракт «{0}» разорван. Неустойка ${1:0}", "Contract \"{0}\" terminated. Penalty ${1:0}" } },
            { "msg.contractOffer", new[] { "Новое письмо на ноутбуке: предложение от «{0}»", "New mail on the laptop: an offer from \"{0}\"" } },
            { "msg.contractAccepted", new[] { "Контракт с «{0}» подписан", "Contract with \"{0}\" signed" } },
            { "msg.contractPenalty", new[] { "Машина по контракту уехала без топлива. Штраф ${0:0}", "A contract vehicle left without fuel. Penalty ${0:0}" } },
            { "msg.contractCompleted", new[] { "Контракт выполнен! Бонус ${0:0}", "Contract completed! Bonus ${0:0}" } },
            { "msg.contractCancelled", new[] { "«{0}» расторг контракт: слишком много срывов", "\"{0}\" cancelled the contract: too many misses" } },
            { "card.contract", new[] { "по контракту {0}", "contract {0}" } },
            { "hint.Laptop", new[] { "E — открыть ноутбук", "E — open the laptop" } },
            { "laptop.title", new[] { "{0} — день {1} — ${2:0}", "{0} — day {1} — ${2:0}" } },
            { "laptop.app.Mail", new[] { "Почта", "Mail" } },
            { "laptop.app.Bank", new[] { "Банк", "Bank" } },
            { "laptop.app.Competitor", new[] { "Конкурент", "Competitor" } },
            { "laptop.app.Regulars", new[] { "Клиенты", "Regulars" } },
            { "laptop.app.Stats", new[] { "Статистика", "Statistics" } },
            { "laptop.mail.offers", new[] { "Предложения", "Offers" } },
            { "laptop.mail.noOffers", new[] { "Новых предложений нет. Они приходят раз в пару дней.", "No new offers. They arrive every couple of days." } },
            { "laptop.mail.active", new[] { "Действующие контракты ({0} из {1})", "Active contracts ({0} of {1})" } },
            { "laptop.mail.noActive", new[] { "Контрактов пока нет.", "No contracts yet." } },
            { "laptop.contract.terms", new[] { "{0} машин в день, {1} по ${2:0.00}/л (рынок ${3:0.00}), {4} дн.", "{0} vehicles a day, {1} at ${2:0.00}/L (market ${3:0.00}), {4} days" } },
            { "laptop.contract.stakes", new[] { "Штраф за сорванную машину ${0:0}, бонус в конце ${1:0}. Предложение действует ещё {2} дн.", "Penalty per missed vehicle ${0:0}, bonus at the end ${1:0}. The offer expires in {2} days." } },
            { "laptop.contract.accept", new[] { "Подписать", "Sign" } },
            { "laptop.contract.decline", new[] { "Отказаться", "Decline" } },
            { "laptop.contract.progress", new[] { "Осталось {0} дн. Обслужено {1}, сорвано {2} из {3}. Цена ${4:0.00}/л", "{0} days left. Served {1}, missed {2} of {3}. Price ${4:0.00}/L" } },
            { "laptop.contract.schedule", new[] { "Расписание: {0}, топливо {1}", "Schedule: {0}, fuel {1}" } },
            { "laptop.contract.daily", new[] { "каждый день в {0}:00, машин: {1}", "every day at {0}:00, {1} vehicles" } },
            { "laptop.contract.every", new[] { "каждые {0} ч с {1}:00 до {2}:00, машин: {3}", "every {0} h from {1}:00 to {2}:00, {3} vehicles" } },
            { "laptop.contract.cancel", new[] { "Разорвать (−${0:0})", "Terminate (−${0:0})" } },
            { "laptop.contract.confirmCancel", new[] { "Точно разорвать?", "Really terminate?" } },
            { "laptop.bank.heading", new[] { "Банк — сложность: {0}", "Bank — difficulty: {0}" } },
            { "laptop.bank.loan", new[] { "Кредит", "Loan" } },
            { "laptop.bank.offer", new[] { "${0:0} под {1:0}% на {2} нед. — ${3:0} в неделю", "${0:0} at {1:0}% for {2} weeks — ${3:0} a week" } },
            { "laptop.bank.take", new[] { "Взять ${0:0}", "Take ${0:0}" } },
            { "laptop.bank.repay", new[] { "Погасить за ${0:0}", "Repay for ${0:0}" } },
            { "laptop.bank.insurance", new[] { "Страховка", "Insurance" } },
            { "laptop.bank.insured", new[] { "Оформлена: ${0:0} в неделю, покрывает {1:0}% краж", "Active: ${0:0} a week, covers {1:0}% of thefts" } },
            { "laptop.bank.notInsured", new[] { "Нет. Стоит ${0:0} в неделю, покрывает {1:0}% краж", "None. Costs ${0:0} a week, covers {1:0}% of thefts" } },
            { "laptop.bank.insuranceOn", new[] { "Оформить", "Take out" } },
            { "laptop.bank.insuranceOff", new[] { "Отменить", "Cancel" } },
            { "laptop.bank.bills", new[] { "Счета и налоги", "Bills and taxes" } },
            { "laptop.rival.heading", new[] { "PetroMax через дорогу", "PetroMax across the road" } },
            { "laptop.rival.prices", new[] { "Цены", "Prices" } },
            { "laptop.rival.priceLine", new[] { "{0}: мы ${1:0.00}, они ${2:0.00}, рынок ${3:0.00}", "{0}: us ${1:0.00}, them ${2:0.00}, market ${3:0.00}" } },
            { "laptop.rival.market", new[] { "Рынок", "Market" } },
            { "laptop.rival.buyout", new[] { "Выкуп", "Buyout" } },
            { "laptop.rival.buyoutText", new[] { "Можно выкупить PetroMax за ${0:0}: все водители трассы будут твоими.", "You can buy out PetroMax for ${0:0}: every driver on the road will be yours." } },
            { "laptop.rival.buy", new[] { "Выкупить за ${0:0}", "Buy out for ${0:0}" } },
            { "laptop.rival.confirm", new[] { "Точно выкупить?", "Really buy out?" } },
            { "laptop.regulars.heading", new[] { "Постоянные клиенты — знакомы {0} из {1}", "Regulars — met {0} of {1}" } },
            { "laptop.regulars.line", new[] { "{0}, около {1}:00, визитов {2}  {3}", "{0}, around {1}:00, {2} visits  {3}" } },
            { "laptop.stats.heading", new[] { "Статистика", "Statistics" } },
            { "laptop.stats.money", new[] { "Деньги", "Money" } },
            { "laptop.stats.station", new[] { "Станция", "Station" } },
            { "laptop.stats.noReviews", new[] { "Отзывов пока нет.", "No reviews yet." } },

            // Living staff
            { "shift.Day", new[] { "дневная смена (7–19)", "day shift (7–19)" } },
            { "shift.Night", new[] { "ночная смена (19–7)", "night shift (19–7)" } },
            { "trait.None", new[] { "без особенностей", "no quirks" } },
            { "trait.Chatty", new[] { "болтун", "chatty" } },
            { "trait.Pedant", new[] { "педант", "pedant" } },
            { "trait.NightOwl", new[] { "сова", "night owl" } },
            { "trait.Tireless", new[] { "двужильный", "tireless" } },
            { "trait.None.desc", new[] { "Обычный работник.", "An ordinary worker." } },
            { "trait.Chatty.desc", new[] { "Клиентам нравится поболтать (+репутация), но работает медленнее.", "Customers enjoy the chat (+reputation), but works slower." } },
            { "trait.Pedant.desc", new[] { "Ходит медленно, зато делает всё основательно.", "Walks slowly but does every job thoroughly." } },
            { "trait.NightOwl.desc", new[] { "Ночью работает на 30% лучше, днём чуть хуже.", "Works 30% better at night, a bit worse by day." } },
            { "trait.Tireless.desc", new[] { "Устаёт почти вдвое медленнее.", "Gets tired almost half as fast." } },
            { "mood.0", new[] { "на грани увольнения", "about to quit" } },
            { "mood.1", new[] { "недоволен", "unhappy" } },
            { "mood.2", new[] { "нормально", "okay" } },
            { "mood.3", new[] { "доволен", "happy" } },
            { "panel.staff.state", new[] { "    {0}, {1}, силы {2:0}%, настроение: {3}, {4}", "    {0}, {1}, energy {2:0}%, mood: {3}, {4}" } },
            { "panel.staff.onShift", new[] { "на смене", "on shift" } },
            { "panel.staff.offShift", new[] { "дома", "at home" } },
            { "panel.staff.laptopHint", new[] { "Похвалить, обучить, поднять зарплату и сменить смену — на ноутбуке (N).", "Praise, train, raise pay and change shifts on the laptop (N)." } },
            { "msg.workerQuit", new[] { "{0} {1} уходит с работы: настроение хуже некуда", "{0} {1} quit: the mood was too bad" } },
            { "msg.alreadyPraised", new[] { "{0}: сегодня уже хвалили", "{0} was already praised today" } },
            { "msg.praised", new[] { "{0}: «Спасибо!» — настроение лучше", "{0} is glad to be praised: mood up" } },
            { "msg.trainingMax", new[] { "{0}: больше курсов не нужно", "{0}: no more courses needed" } },
            { "msg.trained", new[] { "{0}: курсы пройдены, навык {1:0}%", "{0} finished a course: skill {1:0}%" } },
            { "msg.raised", new[] { "{0} получает прибавку: ${1:0} в день", "{0} gets a raise: ${1:0} a day" } },
            { "msg.shiftChanged", new[] { "{0} теперь работает: {1}", "{0} now works the {1}" } },
            { "laptop.app.Staff", new[] { "Персонал", "Staff" } },
            { "laptop.staff.heading", new[] { "Персонал — {0} из {1}", "Staff — {0} of {1}" } },
            { "laptop.staff.title", new[] { "{0} — {1}", "{0} — {1}" } },
            { "laptop.staff.line", new[] { "Навык {0:0.00}, ${1:0}/день, стаж {2} дн. — {3}. Силы {4:0}%, настроение: {5}", "Skill {0:0.00}, ${1:0}/day, {2} days — {3}. Energy {4:0}%, mood: {5}" } },
            { "laptop.staff.candidate", new[] { "Навык {0:0.00}, просит ${1:0}/день, {2}", "Skill {0:0.00}, asks ${1:0}/day, {2}" } },
            { "laptop.staff.praise", new[] { "Похвалить", "Praise" } },
            { "laptop.staff.train", new[] { "Курсы ${0:0}", "Course ${0:0}" } },
            { "laptop.staff.raise", new[] { "Прибавка → ${0:0}", "Raise → ${0:0}" } },
            { "laptop.staff.shift", new[] { "Сменить смену", "Switch shift" } },
            { "laptop.staff.fire", new[] { "Уволить", "Fire" } },
            { "laptop.staff.confirmFire", new[] { "Точно уволить?", "Really fire?" } },
            { "laptop.staff.hire", new[] { "Нанять за ${0:0}", "Hire for ${0:0}" } },

            // Expiry, suppliers and theft
            { "supplier.Cheap", new[] { "Дешёвый поставщик", "Cheap supplier" } },
            { "supplier.Reliable", new[] { "Надёжный поставщик", "Reliable supplier" } },
            { "supplier.Cheap.desc", new[] { "закупка на 20% дешевле, доставка в 1,5 раза дольше, иногда привозит не всё", "20% cheaper, 1.5× slower, sometimes delivers less" } },
            { "supplier.Reliable.desc", new[] { "закупка на 10% дороже, доставка быстрее, всегда полностью", "10% dearer, faster, always complete" } },
            { "msg.supplier", new[] { "Теперь заказываем у: {0}", "Now ordering from: {0}" } },
            { "msg.promoOn", new[] { "Акция «2 по цене 1»: {0}", "\"2 for 1\" promo: {0}" } },
            { "msg.promoOff", new[] { "Акция закончена: {0}", "Promo ended: {0}" } },
            { "msg.spoiled", new[] { "Списано {0:0} шт. просрочки: {1}", "{0:0} expired items written off: {1}" } },
            { "msg.short", new[] { "Поставщик недовёз {0:0} шт.: {1}", "The supplier came {0:0} short: {1}" } },
            { "msg.suspicious", new[] { "Подозрительный покупатель зашёл в магазин! Встань у двери", "A suspicious customer went into the shop! Stand by the door" } },
            { "msg.shoplifterCaught", new[] { "Воришку поймали на кассе, пришлось заплатить", "The shoplifter was caught at the till and had to pay" } },
            { "msg.goodsStolen", new[] { "Из магазина вынесли товар на ${0:0}", "Goods worth ${0:0} were stolen from the shop" } },
            { "msg.robbery", new[] { "Ночью ограбили кассу: −${0:0}", "The till was robbed tonight: −${0:0}" } },
            { "msg.robberyPrevented", new[] { "Ночью пытались ограбить кассу, но не вышло — свет, камеры и смена спугнули грабителей", "Someone tried to rob the till tonight, but the lights, cameras and night staff scared them off" } },
            { "msg.inspectionExpired", new[] { "Инспекция нашла просрочку на полках: штраф ${0:0}", "The inspector found expired food on the shelves: fine ${0:0}" } },
            { "panel.store.age", new[] { " — возраст {0:0}/{1:0} дн.", " — age {0:0}/{1:0} days" } },
            { "panel.store.expired", new[] { " — ПРОСРОЧКА ({0:0}/{1:0} дн.)", " — EXPIRED ({0:0}/{1:0} days)" } },
            { "panel.store.promo", new[] { " — 2 по цене 1", " — 2 for 1" } },
            { "panel.store.supplier", new[] { "P — акция «2 по цене 1». Поставщик: {0} (сменить — на ноутбуке)", "P — \"2 for 1\" promo. Supplier: {0} (change it on the laptop)" } },
            { "laptop.app.Suppliers", new[] { "Поставщики", "Suppliers" } },
            { "laptop.suppliers.heading", new[] { "Поставщики и склад", "Suppliers and stock" } },
            { "laptop.suppliers.current", new[] { "Сейчас: {0}", "Current: {0}" } },
            { "laptop.suppliers.stock", new[] { "На полке {0}/{1}, продаём по ${2:0.00}, закупка ${3:0.00}, в пути {4}", "On the shelf {0}/{1}, selling at ${2:0.00}, buying at ${3:0.00}, on the way {4}" } },
            { "laptop.suppliers.age", new[] { "Возраст партии {0:0} из {1:0} дн.", "Stock age {0:0} of {1:0} days" } },
            { "laptop.suppliers.expired", new[] { "ПРОСРОЧКА: {0:0} из {1:0} дн. — ночью половину спишут", "EXPIRED: {0:0} of {1:0} days — half is written off tonight" } },
            { "laptop.suppliers.order", new[] { "Заказать {0} шт. (${1:0})", "Order {0} (${1:0})" } },
            { "laptop.suppliers.promoOn", new[] { "Акция 2 по цене 1", "2 for 1 promo" } },
            { "laptop.suppliers.promoOff", new[] { "Снять акцию", "End promo" } },
        };
    }
}
