using System.Collections.Generic;

namespace GasStation.Localization
{
    /// <summary>
    /// Source of all UI strings (Russian and English). The editor menu
    /// "GasStation/Localization/Setup" writes them into the Unity Localization string table "GasStation";
    /// at runtime the table is used, and this dictionary is the fallback when the package is not set up.
    /// Strings use string.Format placeholders ({0}, {0:0}, …).
    /// </summary>
    public static class LocTable
    {
        public const string TableName = "GasStation";

        public static readonly Dictionary<string, string[]> Entries = new()
        {
            // Fuel, products
            { "fuel.Petrol92", new[] { "АИ-92", "Regular 92" } },
            { "fuel.Petrol95", new[] { "АИ-95", "Premium 95" } },
            { "fuel.Diesel", new[] { "ДТ", "Diesel" } },
            { "product.Water", new[] { "Вода", "Water" } },
            { "product.Coffee", new[] { "Кофе", "Coffee" } },
            { "product.Snacks", new[] { "Снеки", "Snacks" } },
            { "product.MotorOil", new[] { "Моторное масло", "Motor oil" } },
            { "product.Souvenir", new[] { "Сувениры", "Souvenirs" } },

            // Upgrades
            { "upgrade.name.PumpSpeed", new[] { "Быстрые насосы", "Fast pumps" } },
            { "upgrade.name.TankCapacity", new[] { "Большие резервуары", "Bigger tanks" } },
            { "upgrade.name.Comfort", new[] { "Навес и кофе", "Shade and coffee" } },
            { "upgrade.name.Advertising", new[] { "Реклама", "Advertising" } },
            { "upgrade.name.Attendant", new[] { "Заправщик", "Attendant" } },
            { "upgrade.name.ExtraPump", new[] { "Новая колонка", "Extra pump" } },
            { "upgrade.name.Janitor", new[] { "Уборщик", "Janitor" } },
            { "upgrade.name.Mechanic", new[] { "Механик", "Mechanic" } },
            { "upgrade.name.CarWash", new[] { "Автомойка", "Car wash" } },
            { "upgrade.name.SupplyManager", new[] { "Завхоз", "Supply manager" } },
            { "upgrade.name.TruckParking", new[] { "Стоянка для фур", "Truck parking" } },
            { "upgrade.name.TireService", new[] { "Шиномонтаж", "Tire service" } },
            { "upgrade.name.Motel", new[] { "Мотель", "Motel" } },
            { "upgrade.desc.PumpSpeed", new[] { "+50% скорости заправки", "+50% fueling speed" } },
            { "upgrade.desc.TankCapacity", new[] { "+1000 л к каждому резервуару", "+1000 L to every tank" } },
            { "upgrade.desc.Comfort", new[] { "клиенты ждут на 20% дольше", "customers wait 20% longer" } },
            { "upgrade.desc.Advertising", new[] { "+25% клиентов", "+25% customers" } },
            { "upgrade.desc.ExtraPump", new[] { "открывает ещё одну колонку", "opens one more pump" } },
            { "upgrade.desc.CarWash", new[] { "открывает мойку, уровни — быстрее и дороже", "opens the car wash; levels are faster and pricier" } },
            { "upgrade.desc.SupplyManager", new[] { "сам заказывает топливо и товар; ур.2 −10%, ур.3 быстрее; $50/день", "reorders fuel and goods; lvl 2 −10%, lvl 3 faster; $50/day" } },
            { "upgrade.desc.TruckParking", new[] { "+2 места для ночёвки дальнобойщиков", "+2 overnight spots for truckers" } },
            { "upgrade.desc.TireService", new[] { "меняете шины за деньги; уровни — быстрее и дороже", "change tires for money; levels are faster and pricier" } },
            { "upgrade.desc.Motel", new[] { "+2 номера для ночёвки путешественников, номера дороже", "+2 rooms for travellers, pricier rooms" } },

            // Staff
            { "role.Attendant", new[] { "заправщик", "attendant" } },
            { "role.Janitor", new[] { "уборщик", "janitor" } },
            { "role.Mechanic", new[] { "механик", "mechanic" } },
            { "role.Cashier", new[] { "кассир", "cashier" } },
            { "duty.Attendant", new[] { "сам заправляет машины", "fuels cars" } },
            { "duty.Janitor", new[] { "убирает мусор и туалет", "cleans litter and the restroom" } },
            { "duty.Mechanic", new[] { "чинит колонки, меняет шины", "repairs pumps, changes tires" } },
            { "duty.Cashier", new[] { "ускоряет покупки в магазине", "speeds up shopping" } },
            { "reference.2", new[] { "отличные рекомендации", "excellent references" } },
            { "reference.1", new[] { "обычные рекомендации", "average references" } },
            { "reference.0", new[] { "сомнительные рекомендации", "dubious references" } },
            { "staff.name.0", new[] { "Иван", "John" } },
            { "staff.name.1", new[] { "Ольга", "Olivia" } },
            { "staff.name.2", new[] { "Пётр", "Peter" } },
            { "staff.name.3", new[] { "Анна", "Anna" } },
            { "staff.name.4", new[] { "Сергей", "Sam" } },
            { "staff.name.5", new[] { "Мария", "Mary" } },
            { "staff.name.6", new[] { "Алексей", "Alex" } },
            { "staff.name.7", new[] { "Елена", "Helen" } },
            { "staff.name.8", new[] { "Дмитрий", "Daniel" } },
            { "staff.name.9", new[] { "Наталья", "Natalie" } },
            { "staff.name.10", new[] { "Андрей", "Andrew" } },
            { "staff.name.11", new[] { "Татьяна", "Tina" } },
            { "staff.name.12", new[] { "Михаил", "Michael" } },
            { "staff.name.13", new[] { "Ирина", "Irene" } },
            { "staff.name.14", new[] { "Николай", "Nick" } },
            { "staff.name.15", new[] { "Светлана", "Susan" } },

            // Paint, customers
            { "scheme.0", new[] { "Облезлая краска", "Peeling paint" } },
            { "scheme.1", new[] { "Классика", "Classic" } },
            { "scheme.2", new[] { "Пустынный закат", "Desert sunset" } },
            { "scheme.3", new[] { "Неон 80-х", "80s neon" } },
            { "customer.Regular", new[] { "клиент", "customer" } },
            { "customer.Trucker", new[] { "дальнобойщик", "trucker" } },
            { "customer.Hurry", new[] { "торопыга", "in a hurry" } },
            { "customer.Tourist", new[] { "турист", "tourist" } },
            { "customer.Thief", new[] { "подозрительный тип", "shady type" } },

            // Quests
            { "quest.title.0", new[] { "Заброшенная заправка", "Abandoned station" } },
            { "quest.title.1", new[] { "Первые клиенты", "First customers" } },
            { "quest.title.2", new[] { "Наводим порядок", "Tidying up" } },
            { "quest.title.3", new[] { "Бензовоз", "Fuel truck" } },
            { "quest.title.4", new[] { "Первое вложение", "First investment" } },
            { "quest.title.5", new[] { "Постоянные клиенты", "Regulars" } },
            { "quest.title.6", new[] { "Генеральная уборка", "Spring cleaning" } },
            { "quest.title.7", new[] { "Хорошая репутация", "Good name" } },
            { "quest.title.8", new[] { "Прибыльный день", "Profitable day" } },
            { "quest.title.9", new[] { "Расширение", "Expansion" } },
            { "quest.title.10", new[] { "Идеальная чистота", "Spotless" } },
            { "quest.title.11", new[] { "Колонка не работает", "Broken pump" } },
            { "quest.title.12", new[] { "Растущая слава", "Rising fame" } },
            { "quest.title.13", new[] { "Держи вора!", "Stop, thief!" } },
            { "quest.title.14", new[] { "Первые покупки", "First sales" } },
            { "quest.title.15", new[] { "Автомойка", "Car wash" } },
            { "quest.title.16", new[] { "Туалет", "Restroom" } },
            { "quest.title.17", new[] { "Ночлег", "A place to sleep" } },
            { "quest.title.18", new[] { "Новый облик", "Fresh look" } },
            { "quest.title.19", new[] { "Шиномонтаж", "Tire service" } },
            { "quest.title.20", new[] { "Первый сотрудник", "First employee" } },
            { "quest.title.21", new[] { "Мотель у дороги", "Roadside motel" } },
            { "quest.title.daily", new[] { "Задание дня", "Daily task" } },
            { "quest.goal.CollectTrash", new[] { "Собери мусор (E): {0}/{1:0}", "Pick up litter (E): {0}/{1:0}" } },
            { "quest.goal.ServeCustomers", new[] { "Обслужи клиентов: {0}/{1:0}", "Serve customers: {0}/{1:0}" } },
            { "quest.goal.OrderFuel", new[] { "Закажи бензовоз (O): {0}/{1:0}", "Order a fuel truck (O): {0}/{1:0}" } },
            { "quest.goal.BuyUpgrade", new[] { "Купи улучшение (Tab): {0}/{1:0}", "Buy an upgrade (Tab): {0}/{1:0}" } },
            { "quest.goal.Cleanliness", new[] { "Доведи чистоту до {1:0}%: сейчас {0}%", "Get cleanliness to {1:0}%: now {0}%" } },
            { "quest.goal.Reputation", new[] { "Подними репутацию до {1:0}%: сейчас {0}%", "Raise reputation to {1:0}%: now {0}%" } },
            { "quest.goal.DayIncome", new[] { "Заработай за день ${1:0}: сейчас ${0}", "Earn ${1:0} in one day: now ${0}" } },
            { "quest.goal.OpenPumps", new[] { "Открой новую колонку (Tab): {0}/1", "Open a new pump (Tab): {0}/1" } },
            { "quest.goal.RepairPump", new[] { "Почини колонку (E рядом со сломанной): {0}/{1:0}", "Repair a pump (E next to it): {0}/{1:0}" } },
            { "quest.goal.StationLevel", new[] { "Подними уровень станции до {1:0}: сейчас {0}", "Reach station level {1:0}: now {0}" } },
            { "quest.goal.CatchThief", new[] { "Стой рядом с машиной вора, когда он заправляется: {0}/1", "Stand next to a thief's car while it fuels: {0}/1" } },
            { "quest.goal.SellProducts", new[] { "Продай товары в магазине (M — ассортимент): {0}/{1:0}", "Sell goods in the shop (M — stock): {0}/{1:0}" } },
            { "quest.goal.OpenCarWash", new[] { "Открой автомойку (Tab): {0}/1", "Open the car wash (Tab): {0}/1" } },
            { "quest.goal.CleanRestroom", new[] { "Убери туалет (E у двери): {0}/1", "Clean the restroom (E at the door): {0}/1" } },
            { "quest.goal.HostTruckers", new[] { "Прими дальнобойщиков на ночь (Стоянка для фур): {0}/{1:0}", "Host truckers overnight (Truck parking): {0}/{1:0}" } },
            { "quest.goal.PaintStation", new[] { "Перекрась станцию (C): {0}/1", "Repaint the station (C): {0}/1" } },
            { "quest.goal.ChangeTires", new[] { "Поменяй шины клиентам (E у бокса шиномонтажа): {0}/{1:0}", "Change customers' tires (E at the tire bay): {0}/{1:0}" } },
            { "quest.goal.HireWorker", new[] { "Найми сотрудника (H): {0}/1", "Hire an employee (H): {0}/1" } },
            { "quest.goal.HostGuests", new[] { "Прими гостей в мотеле (Tab → «Мотель»): {0}/{1:0}", "Host motel guests (Tab → Motel): {0}/{1:0}" } },
            { "quest.reward.both", new[] { "${0:0} и +{1:0}% репутации", "${0:0} and +{1:0}% reputation" } },
            { "quest.reward.money", new[] { "${0:0}", "${0:0}" } },
            { "quest.reward.reputation", new[] { "+{0:0}% репутации", "+{0:0}% reputation" } },
            { "quest.header", new[] { "Задание: {0}", "Task: {0}" } },
            { "quest.reward", new[] { "Награда: {0}", "Reward: {0}" } },
            { "quest.completed", new[] { "Задание выполнено: {0}! Награда: {1}", "Task complete: {0}! Reward: {1}" } },

            // HUD: status
            { "hud.help", new[] {
                "WASD — ходить   E / ЛКМ — действие   1/2/3 — топливо   +/- — цена   O — заказать 500 л\nTab — улучшения   M — магазин   C — покраска   H — персонал   J — достижения   L — язык   F5 — сохранить   F9 — загрузить   F10 ×2 — новая игра",
                "WASD — walk   E / LMB — action   1/2/3 — fuel   +/- — price   O — order 500 L\nTab — upgrades   M — shop   C — paint   H — staff   J — achievements   L — language   F5 — save   F9 — load   F10 ×2 — new game" } },
            { "hud.day", new[] { "День {0}   {1:00}:{2:00}", "Day {0}   {1:00}:{2:00}" } },
            { "hud.money", new[] { "Деньги: ${0:0}", "Money: ${0:0}" } },
            { "hud.reputation", new[] { "Репутация: {0:0}%", "Reputation: {0:0}%" } },
            { "hud.cleanliness", new[] { "Чистота: {0:0}% (мусора: {1})", "Cleanliness: {0:0}% (litter: {1})" } },
            { "hud.staff", new[] { "Персонал: {0} чел., зарплаты ${1:0}/день", "Staff: {0}, wages ${1:0}/day" } },
            { "hud.level.max", new[] { "Уровень станции: {0} (макс.)", "Station level: {0} (max)" } },
            { "hud.level", new[] { "Уровень станции: {0}   опыт {1:0}/{2:0}", "Station level: {0}   xp {1:0}/{2:0}" } },
            { "hud.event", new[] { "Событие: {0} (ещё {1:0.0} ч)", "Event: {0} ({1:0.0} h left)" } },
            { "event.RushHour", new[] { "Час пик", "Rush hour" } },
            { "event.Sandstorm", new[] { "Песчаная буря", "Sandstorm" } },
            { "hud.today", new[] { "Сегодня: +${0:0} / -${1:0}", "Today: +${0:0} / -${1:0}" } },
            { "hud.served", new[] { "Обслужено: {0}   Уехали: {1}", "Served: {0}   Lost: {1}" } },
            { "hud.fuel", new[] { "{0}: {1:0}/{2:0} л   ${3:0.00} (рынок ${4:0.00})", "{0}: {1:0}/{2:0} L   ${3:0.00} (market ${4:0.00})" } },
            { "hud.fuel.pending", new[] { "   +{0:0} л в пути", "   +{0:0} L on the way" } },

            // HUD: facilities and pumps
            { "hud.queue", new[] { "Очередь: {0}   Машин на станции: {1}", "Queue: {0}   Cars on site: {1}" } },
            { "hud.wash", new[] { "Мойка: {0}", "Car wash: {0}" } },
            { "hud.wash.closed", new[] { "закрыта (улучшение «Автомойка»)", "closed (Car wash upgrade)" } },
            { "hud.wash.working", new[] { "моет машину, ещё {0:0} с", "washing, {0:0} s left" } },
            { "hud.wash.arriving", new[] { "машина подъезжает", "car arriving" } },
            { "hud.free.f", new[] { "свободна", "free" } },
            { "hud.free.m", new[] { "свободен", "free" } },
            { "hud.parking.closed", new[] { "Стоянка для фур: закрыта (улучшение «Стоянка для фур»)", "Truck parking: closed (Truck parking upgrade)" } },
            { "hud.parking", new[] { "Стоянка для фур: {0}/{1} мест занято", "Truck parking: {0}/{1} spots taken" } },
            { "hud.tires", new[] { "Шиномонтаж: {0}", "Tire service: {0}" } },
            { "hud.tires.closed", new[] { "закрыт (улучшение «Шиномонтаж»)", "closed (Tire service upgrade)" } },
            { "hud.tires.working", new[] { "меняем шины, ещё {0:0} с", "changing tires, {0:0} s left" } },
            { "hud.tires.waiting", new[] { "МАШИНА ЖДЁТ — E у бокса", "CAR WAITING — E at the bay" } },
            { "hud.motel.closed", new[] { "Мотель: закрыт (улучшение «Мотель»)", "Motel: closed (Motel upgrade)" } },
            { "hud.motel", new[] { "Мотель: {0}/{1} номеров занято", "Motel: {0}/{1} rooms taken" } },
            { "hud.motel.dirty", new[] { ", грязных {0} — E у ресепшена", ", {0} dirty — E at reception" } },
            { "hud.restroom.disgusting", new[] { "Туалет: ОТВРАТИТЕЛЬНО", "Restroom: DISGUSTING" } },
            { "hud.restroom", new[] { "Туалет: грязь {0:0}%", "Restroom: {0:0}% dirty" } },
            { "hud.pump", new[] { "Колонка {0}: ", "Pump {0}: " } },
            { "hud.pump.locked", new[] { "закрыта (улучшение «Новая колонка»)", "closed (Extra pump upgrade)" } },
            { "hud.pump.broken", new[] { "СЛОМАНА — почините (E рядом)", "BROKEN — repair it (E nearby)" } },
            { "hud.pump.wear", new[] { " [износ {0:0}%]", " [wear {0:0}%]" } },
            { "hud.pump.car", new[] { "{0} {1}, {2} {3:0}/{4:0} л, терпение {5:0}%{6}", "{0} {1}, {2} {3:0}/{4:0} L, patience {5:0}%{6}" } },
            { "carstate.DrivingToPump", new[] { "подъезжает", "arriving" } },
            { "carstate.WaitingForService", new[] { "ждёт заправки", "waiting for fuel" } },
            { "carstate.Fueling", new[] { "заправляется", "fueling" } },
            { "carstate.Shopping", new[] { "водитель в магазине", "driver in the shop" } },
            { "carstate.ReadyToLeave", new[] { "уезжает", "leaving" } },

            // HUD: center
            { "hud.report", new[] {
                "Итоги дня {0}\nДоход: ${1:0}   Расходы: ${2:0}\nПрибыль: ${3:0}\nОбслужено: {4}   Уехали: {5}",
                "Day {0} summary\nIncome: ${1:0}   Expenses: ${2:0}\nProfit: ${3:0}\nServed: {4}   Lost: {5}" } },
            { "hint.CanStartFueling", new[] { "[E / ЛКМ] Заправить", "[E / LMB] Fuel the car" } },
            { "hint.Fueling", new[] { "Идёт заправка...", "Fueling..." } },
            { "hint.CarArriving", new[] { "Машина подъезжает", "Car arriving" } },
            { "hint.Trash", new[] { "[E / ЛКМ] Убрать мусор", "[E / LMB] Pick up litter" } },
            { "hint.Restroom", new[] { "[E / ЛКМ] Убрать туалет", "[E / LMB] Clean the restroom" } },
            { "hint.Tires", new[] { "[E / ЛКМ] Поменять шины", "[E / LMB] Change tires" } },
            { "hint.MotelRoom", new[] { "[E / ЛКМ] Убрать номер в мотеле", "[E / LMB] Clean a motel room" } },
            { "hint.Repair", new[] { "[E / ЛКМ] Чинить колонку (${0:0} за шаг)", "[E / LMB] Repair the pump (${0:0} per step)" } },

            // HUD: panels
            { "panel.upgrades", new[] { "УЛУЧШЕНИЯ, стр. {0}/{1} (цифра — купить, Tab — дальше / закрыть)", "UPGRADES, page {0}/{1} (digit — buy, Tab — next / close)" } },
            { "panel.upgrades.line", new[] { "{0}. {1} [{2}/{3}] — {4}: {5}", "{0}. {1} [{2}/{3}] — {4}: {5}" } },
            { "panel.max", new[] { "макс.", "max" } },
            { "panel.needLevel", new[] { "нужен уровень {0}", "needs level {0}" } },
            { "panel.price", new[] { "${0:0}", "${0:0}" } },
            { "panel.staff", new[] { "ПЕРСОНАЛ {0}/{1} (1–3 — нанять, 4–9 ×2 — уволить, H — закрыть)", "STAFF {0}/{1} (1–3 — hire, 4–9 ×2 — fire, H — close)" } },
            { "panel.staff.candidates", new[] { "Кандидаты сегодня:", "Today's applicants:" } },
            { "panel.staff.candidate", new[] { "{0}. {1}, {2} ({3}), навык {4:0.00}, ${5:0}/день, {6}; найм ${7:0}", "{0}. {1}, {2} ({3}), skill {4:0.00}, ${5:0}/day, {6}; hiring ${7:0}" } },
            { "panel.staff.none", new[] { "Сотрудников пока нет.", "No employees yet." } },
            { "panel.staff.working", new[] { "Работают:", "Employed:" } },
            { "panel.staff.worker", new[] { "{0}. {1}, {2}, навык {3:0.00}, ${4:0}/день, стаж {5} дн.", "{0}. {1}, {2}, skill {3:0.00}, ${4:0}/day, {5} days" } },
            { "panel.staff.confirmFire", new[] { "Нажмите {0} ещё раз, чтобы уволить: {1}", "Press {0} again to fire {1}" } },
            { "panel.paint", new[] { "ПОКРАСКА (цифра — перекрасить, C — закрыть)", "PAINT (digit — repaint, C — close)" } },
            { "panel.paint.current", new[] { "Сейчас: «{0}», клиентов {1:+0;-0;0}%", "Now: \"{0}\", customers {1:+0;-0;0}%" } },
            { "panel.paint.line", new[] { "{0}. «{1}» — {2}, клиентов {3:+0;-0;0}%", "{0}. \"{1}\" — {2}, customers {3:+0;-0;0}%" } },
            { "panel.paint.current.short", new[] { "уже так", "current" } },
            { "panel.store", new[] { "МАГАЗИН (1–5 — товар, +/- — цена, O — заказать {0} шт., M — закрыть)", "SHOP (1–5 — item, +/- — price, O — order {0}, M — close)" } },
            { "panel.store.inside", new[] { "Покупателей внутри: {0}", "Shoppers inside: {0}" } },
            { "panel.store.line", new[] { "{0}. {1}: {2}/{3}   ${4:0.00} (закупка ${5:0.00}, обычно ${6:0.00})", "{0}. {1}: {2}/{3}   ${4:0.00} (cost ${5:0.00}, usual ${6:0.00})" } },
            { "panel.store.pending", new[] { "   +{0} в пути", "   +{0} on the way" } },

            // Notifications
            { "msg.confirmNewGame", new[] { "Нажмите F10 ещё раз, чтобы начать заново", "Press F10 again to start over" } },
            { "msg.language", new[] { "Язык: русский", "Language: English" } },
            { "msg.customerAngry", new[] { "Клиент уехал недовольным", "A customer left unhappy" } },
            { "msg.fuelRanOut", new[] { "Закончилось топливо: {0}! Закажите бензовоз (O)", "Out of {0}! Order a fuel truck (O)" } },
            { "msg.fuelDelivered", new[] { "Бензовоз привёз {0:0} л {1}", "The fuel truck delivered {0:0} L of {1}" } },
            { "msg.pumpBroken", new[] { "Колонка {0:0} сломалась! Почините её (E)", "Pump {0:0} broke down! Repair it (E)" } },
            { "msg.pumpRepaired", new[] { "Колонка {0:0} как новая", "Pump {0:0} is as good as new" } },
            { "msg.noMoney", new[] { "Не хватает денег: нужно ${0:0}", "Not enough money: ${0:0} needed" } },
            { "msg.levelUp", new[] { "Уровень станции {0:0}! Открыты новые улучшения и клиенты", "Station level {0:0}! New upgrades and customers unlocked" } },
            { "msg.tip", new[] { "Чаевые: ${0:0}", "Tip: ${0:0}" } },
            { "msg.fuelStolen", new[] { "Вор уехал без оплаты! Потеряно ${0:0}", "A thief drove off without paying! Lost ${0:0}" } },
            { "msg.thiefCaught", new[] { "Вор пойман и заплатил!", "Thief caught — he paid!" } },
            { "msg.market", new[] { "Цены на нефть: {0:+0.0;-0.0;0}%. Проверьте свои цены", "Oil prices: {0:+0.0;-0.0;0}%. Check your prices" } },
            { "msg.vandals", new[] { "Ночью приходили вандалы и намусорили", "Vandals came at night and left a mess" } },
            { "msg.rushHour", new[] { "Час пик: туристы едут толпой!", "Rush hour: tourists are coming!" } },
            { "msg.sandstorm", new[] { "Песчаная буря: клиентов мало, мусора много", "Sandstorm: few customers, lots of litter" } },
            { "msg.inspectionPassed", new[] { "Проверка пройдена! Премия ${0:0}", "Inspection passed! Bonus ${0:0}" } },
            { "msg.inspectionFailed", new[] { "Проверка: грязно! Штраф ${0:0}", "Inspection: dirty! Fine ${0:0}" } },
            { "msg.shopEmpty", new[] { "Покупатель ушёл из магазина ни с чем — закажите товар (M)", "A shopper left empty-handed — order goods (M)" } },
            { "msg.restroomDisgusting", new[] { "Клиент в ужасе от туалета! Уберите его (E у двери)", "A customer is horrified by the restroom! Clean it (E at the door)" } },
            { "msg.workerStole", new[] { "Из кассы пропало ${0:0}. Кто-то из сотрудников нечист на руку…", "${0:0} is missing from the till. Someone on staff is not honest…" } },
            { "msg.truckParked", new[] { "Дальнобойщик встал на ночёвку", "A trucker parked for the night" } },
            { "msg.parkingPaid", new[] { "Дальнобойщик заплатил за ночь: ${0:0}", "A trucker paid for the night: ${0:0}" } },
            { "msg.productsDelivered", new[] { "В магазин привезли товар: {0:0} шт.", "Goods delivered to the shop: {0:0}" } },
            { "msg.motelPaid", new[] { "Гость мотеля заплатил: ${0:0}", "A motel guest paid: ${0:0}" } },
            { "msg.saved", new[] { "Игра сохранена", "Game saved" } },
            { "msg.loaded", new[] { "Игра загружена", "Game loaded" } },
            { "msg.noSave", new[] { "Сохранение не найдено", "No saved game" } },
            { "msg.newGame", new[] { "Новая игра", "New game" } },
            { "msg.continue", new[] { "Продолжаем: день {0}", "Welcome back: day {0}" } },
            { "msg.tankFull", new[] { "Резервуар полон", "The tank is full" } },
            { "msg.fuelOrdered", new[] { "Заказано {0:0} л {1}, привезут через {2:0} с", "Ordered {0:0} L of {1}, arriving in {2:0} s" } },
            { "msg.noShop", new[] { "На станции нет магазина", "There is no shop at the station" } },
            { "msg.shelvesFull", new[] { "{0}: полки заполнены", "{0}: shelves are full" } },
            { "msg.productsOrdered", new[] { "Заказано: {0} × {1}, привезут через {2:0} с", "Ordered {0} × {1}, arriving in {2:0} s" } },
            { "msg.staffFull", new[] { "Штат полон: не больше {0} сотрудников", "Staff is full: at most {0} employees" } },
            { "msg.noMoneyHire", new[] { "Не хватает денег на найм: нужно ${0:0}", "Not enough money to hire: ${0:0} needed" } },
            { "msg.hired", new[] { "Нанят {0}: {1}", "Hired {0}: {1}" } },
            { "msg.fired", new[] { "Уволен {0}: {1}", "Fired {0}: {1}" } },
            { "msg.alreadyPainted", new[] { "Станция уже так покрашена", "The station already has this paint" } },
            { "msg.schemeNeedsLevel", new[] { "«{0}»: нужен уровень станции {1}", "\"{0}\": needs station level {1}" } },
            { "msg.painted", new[] { "Станция перекрашена: «{0}»", "Station repainted: \"{0}\"" } },
            { "msg.upgradeMax", new[] { "{0}: максимальный уровень", "{0}: maximum level" } },
            { "msg.upgradeNeedsLevel", new[] { "{0}: нужен уровень станции {1}", "{0}: needs station level {1}" } },
            { "msg.upgradeBought", new[] { "Куплено: {0}, уровень {1}", "Bought: {0}, level {1}" } },

            // Achievements
            { "achievement.FirstCustomer.name", new[] { "Первый клиент", "First customer" } },
            { "achievement.FirstCustomer.desc", new[] { "Обслужи первого клиента", "Serve your first customer" } },
            { "achievement.Served100.name", new[] { "Сотня", "A hundred" } },
            { "achievement.Served100.desc", new[] { "Обслужи 100 клиентов", "Serve 100 customers" } },
            { "achievement.Served1000.name", new[] { "Тысяча машин", "A thousand cars" } },
            { "achievement.Served1000.desc", new[] { "Обслужи 1000 клиентов", "Serve 1000 customers" } },
            { "achievement.Trash100.name", new[] { "Дворник", "Street sweeper" } },
            { "achievement.Trash100.desc", new[] { "Собери 100 кусков мусора", "Pick up 100 pieces of litter" } },
            { "achievement.Trash1000.name", new[] { "Чистюля", "Neat freak" } },
            { "achievement.Trash1000.desc", new[] { "Собери 1000 кусков мусора", "Pick up 1000 pieces of litter" } },
            { "achievement.Income10K.name", new[] { "Первые $10 000", "First $10,000" } },
            { "achievement.Income10K.desc", new[] { "Заработай $10 000 на клиентах", "Earn $10,000 from customers" } },
            { "achievement.Income100K.name", new[] { "Нефтяной магнат", "Oil baron" } },
            { "achievement.Income100K.desc", new[] { "Заработай $100 000 на клиентах", "Earn $100,000 from customers" } },
            { "achievement.Level5.name", new[] { "Известное место", "Known place" } },
            { "achievement.Level5.desc", new[] { "Достигни 5-го уровня станции", "Reach station level 5" } },
            { "achievement.Level10.name", new[] { "Легенда трассы", "Highway legend" } },
            { "achievement.Level10.desc", new[] { "Достигни 10-го уровня станции", "Reach station level 10" } },
            { "achievement.ThiefCaught.name", new[] { "Шериф", "Sheriff" } },
            { "achievement.ThiefCaught.desc", new[] { "Поймай вора", "Catch a thief" } },
            { "achievement.MotelGuests10.name", new[] { "Гостеприимство", "Hospitality" } },
            { "achievement.MotelGuests10.desc", new[] { "Прими 10 гостей в мотеле", "Host 10 motel guests" } },
            { "achievement.Truckers10.name", new[] { "Друг дальнобойщиков", "Truckers' friend" } },
            { "achievement.Truckers10.desc", new[] { "Прими 10 дальнобойщиков на ночь", "Host 10 truckers overnight" } },
            { "achievement.CarsWashed50.name", new[] { "Блеск", "Shine" } },
            { "achievement.CarsWashed50.desc", new[] { "Помой 50 машин", "Wash 50 cars" } },
            { "achievement.Tires25.name", new[] { "Шинный мастер", "Tire master" } },
            { "achievement.Tires25.desc", new[] { "Поменяй шины 25 раз", "Change tires 25 times" } },
            { "achievement.PerfectDay.name", new[] { "Идеальный день", "Perfect day" } },
            { "achievement.PerfectDay.desc", new[] { "Обслужи за день 20+ клиентов, и чтобы никто не уехал недовольным", "Serve 20+ customers in a day with nobody leaving unhappy" } },
            { "achievement.Tycoon.name", new[] { "Магнат", "Tycoon" } },
            { "achievement.Tycoon.desc", new[] { "Накопи $50 000", "Save up $50,000" } },
            { "achievement.Spotless.name", new[] { "Ни соринки", "Spotless" } },
            { "achievement.Spotless.desc", new[] { "Доведи чистоту станции до 100%", "Get station cleanliness to 100%" } },
            { "achievement.FullStaff.name", new[] { "Полный штат", "Full staff" } },
            { "achievement.FullStaff.desc", new[] { "Найми 6 сотрудников", "Hire 6 employees" } },
            { "panel.achievements", new[] { "ДОСТИЖЕНИЯ {0}/{1} (J — закрыть)", "ACHIEVEMENTS {0}/{1} (J — close)" } },
            { "panel.achievements.line", new[] { "[{0}] {1} — {2}", "[{0}] {1} — {2}" } },
            { "panel.achievements.stats", new[] { "Дней: {0}   клиентов: {1}   заработано: ${2:0}", "Days: {0}   customers: {1}   earned: ${2:0}" } },
            { "msg.achievement", new[] { "Достижение получено: {0}!", "Achievement unlocked: {0}!" } },
            { "meter.reputation", new[] { "Репутация", "Reputation" } },
            { "meter.cleanliness", new[] { "Чистота", "Cleanliness" } },
            { "meter.experience", new[] { "Опыт", "Experience" } },
        };
    }
}
